create or replace view V_COMPONENT_MART(
	JOBNUMBER,
	USERDEFINED6,
	ENTRYDATE,
	DUEDATE,
	DELIVERYDATE,
	PROOFDUEDATE,
	PROOFDELIVERYDATE,
	CREATEDATIM,
	UPDATEDATIM,
	COMPONENTNUMBER,
	COMPONENTTYPE,
	COMPONENT_TYPE,
	FINGOODCODE,
	USEQUANTITYTABLE,
	DISCOUNT,
	MANUALPRESSOUTS,
	ESTIMATENUMBER,
	CHARGEZERO,
	DONTCALCULATE,
	COMPONENTPLANNED,
	MANUALPRICEMETHOD,
	MANUALPRICEOVERRIDE,
	USERDEFINED2,
	USERDEFINED4,
	ID,
	HEADERID,
	TAXJURISDICTION,
	SUM_QUANTITYORDERED,
	SUM_PRODUCTIONMARKUP,
	SUM_MATERIALMARKUP,
	SUM_STOCKMARKUP,
	SUM_TOTALSELLPRICE,
	SUM_DISCOUNTDOLLARS,
	ROW_COUNT,
	QTY_TOTAL_QUANTITY,
	QTY_TOTALCOST,
	QTY_TOTALPRICE,
	QTY_PRODUCTIONCOST,
	QTY_MATERIALCOST,
	QTY_STOCKCOST,
	QTY_OSCOST,
	QTY_PRODUCTIONPRICE,
	QTY_MATERIALPRICE,
	QTY_STOCKPRICE,
	QTY_OSPRICE,
	QTY_DISCOUNTAMOUNT,
	QTY_UNITPRICE,
	QUANTITY_LINE_COUNT,
	UNITCOST_TOTAL_QUANTITY,
	TOTAL_UNITCOST,
	TOTAL_MINIMUMCOST,
	TOTAL_MARKUP,
	TOTAL_UNITPRICEOVERRIDE,
	UNITCOST_PROCESS_COUNT,
	UDFIELD_COUNT,
	DISTINCT_FIELDLABEL_COUNT,
	DISTINCT_SECTION_COUNT
) as
SELECT
    oc.*,

    oq.TOTAL_QUANTITY AS QTY_TOTAL_QUANTITY,
    oq.TOTAL_TOTALCOST AS QTY_TOTALCOST,
    oq.TOTAL_TOTALPRICE AS QTY_TOTALPRICE,
    oq.TOTAL_PRODUCTIONCOST AS QTY_PRODUCTIONCOST,
    oq.TOTAL_MATERIALCOST AS QTY_MATERIALCOST,
    oq.TOTAL_STOCKCOST AS QTY_STOCKCOST,
    oq.TOTAL_OSCOST AS QTY_OSCOST,
    oq.TOTAL_PRODUCTIONPRICE AS QTY_PRODUCTIONPRICE,
    oq.TOTAL_MATERIALPRICE AS QTY_MATERIALPRICE,
    oq.TOTAL_STOCKPRICE AS QTY_STOCKPRICE,
    oq.TOTAL_OSPRICE AS QTY_OSPRICE,
    oq.TOTAL_DISCOUNTAMOUNT AS QTY_DISCOUNTAMOUNT,
    oq.TOTAL_UNITPRICE AS QTY_UNITPRICE,
    oq.QUANTITY_LINE_COUNT,

    uc.TOTAL_QUANTITY AS UNITCOST_TOTAL_QUANTITY,
    uc.TOTAL_UNITCOST,
    uc.TOTAL_MINIMUMCOST,
    uc.TOTAL_MARKUP,
    uc.TOTAL_UNITPRICEOVERRIDE,
    uc.PROCESS_COUNT AS UNITCOST_PROCESS_COUNT,

    udf.UDFIELD_COUNT,
    udf.DISTINCT_FIELDLABEL_COUNT,
    udf.DISTINCT_SECTION_COUNT

FROM DATA_VALIDATION.MART_REVENUE.V_ORDERCOMPONENT_GROUPED oc

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_ORDERQTYTABLE_ANALYTICS oq
    ON oc.JOBNUMBER = oq.JOBNUMBER
   AND oc.ESTIMATENUMBER = oq.ESTIMATENUMBER
   AND oc.COMPONENTNUMBER = oq.COMPONENTNUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_ORDERUNITCOST_COMPONENT_ANALYTICS uc
    ON oc.JOBNUMBER = uc.JOBNUMBER
   AND oc.ESTIMATENUMBER = uc.ESTIMATENUMBER
   AND oc.COMPONENTNUMBER = uc.COMPONENTNUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_ORDERUDFIELDS_JOB_ANALYTICS udf
    ON oc.JOBNUMBER = udf.JOBNUMBER
   AND oc.ESTIMATENUMBER = udf.ESTIMATENUMBER;;
