create or replace view V_MONTHLY_REVENUE_TRENDS(
	ORDER_MONTH,
	PLANTID,
	SALESREPCODE,
	CUSTOMER_COUNT,
	JOB_COUNT,
	COMPONENT_COUNT,
	COMPONENT_REVENUE,
	TOTAL_COST,
	TOTAL_PRICE,
	AR_NETVAL,
	AR_TOTALVAL,
	ESTIMATED_MARGIN
) as
SELECT
    ORDER_MONTH,
    PLANTID,
    SALESREPCODE,

    COUNT(DISTINCT CUSTACCOUNT) AS CUSTOMER_COUNT,
    SUM(JOB_COUNT) AS JOB_COUNT,
    SUM(COMPONENT_COUNT) AS COMPONENT_COUNT,

    SUM(COMPONENT_TOTAL_SELL_PRICE) AS COMPONENT_REVENUE,
    SUM(TOTAL_COST) AS TOTAL_COST,
    SUM(TOTAL_PRICE) AS TOTAL_PRICE,

    SUM(AR_NETVAL) AS AR_NETVAL,
    SUM(AR_TOTALVAL) AS AR_TOTALVAL,

    SUM(COMPONENT_TOTAL_SELL_PRICE) - SUM(TOTAL_COST) AS ESTIMATED_MARGIN

FROM DATA_VALIDATION.MART_REVENUE.MONTHLY_REVENUE_SUMMARY
GROUP BY
    ORDER_MONTH,
    PLANTID,
    SALESREPCODE;;
