create or replace view V_ORDERHEADER_WITH_PRICE_CHANGES(
	JOBNUMBER,
	ESTIMATENUMBER,
	FORMNUMBER,
	CUSTACCOUNT,
	CUSTNAME,
	CUSTSTATE,
	PLANTID,
	ORDERDATE,
	DUEDATE,
	DELIVERYDATE,
	ORDERTYPE,
	PONUMBER,
	PODATE,
	CREATEDATIM,
	UPDATEDATIM,
	JOBSTATUS,
	USERDEFINED1,
	USERDEFINED4,
	USERDEFINED5,
	ESTIMATESTATUS,
	SUM_PREPAYMENT,
	SUM_TOTALCOMPONENTS,
	SUM_TOTALCOMPONENTSQTYCALCULATED,
	SUM_TOTALSELLPRICE,
	SUM_ORDERSELLPRICE,
	SUM_INVOICESELLPRICE,
	SUM_INVOICEDFREIGHTPRICE,
	SUM_CALCULATEDTOTALPRICE,
	SUM_DISCOUNT,
	ROW_COUNT,
	PRICECHANGE_TOTALPRICE,
	PRICECHANGE_PRICEADJUSTMENT,
	PRICECHANGE_ROW_COUNT,
	FIRST_PRICECHANGE_ENTRYDATE,
	LAST_PRICECHANGE_ENTRYDATE,
	FIRST_PRICECHANGE_CREATEDATIM,
	LAST_PRICECHANGE_CREATEDATIM,
	FIRST_PRICECHANGE_UPDATEDATIM,
	LAST_PRICECHANGE_UPDATEDATIM
) as
WITH price_change AS (
    SELECT
        JOBNUMBER,
        ESTIMATENUMBER,

        SUM(TOTALPRICE) AS PRICECHANGE_TOTALPRICE,
        SUM(PRICEADJUSTMENT) AS PRICECHANGE_PRICEADJUSTMENT,
        COUNT(*) AS PRICECHANGE_ROW_COUNT,

        MIN(ENTRYDATE) AS FIRST_PRICECHANGE_ENTRYDATE,
        MAX(ENTRYDATE) AS LAST_PRICECHANGE_ENTRYDATE,
        MIN(CREATEDATIM) AS FIRST_PRICECHANGE_CREATEDATIM,
        MAX(CREATEDATIM) AS LAST_PRICECHANGE_CREATEDATIM,
        MIN(UPDATEDATIM) AS FIRST_PRICECHANGE_UPDATEDATIM,
        MAX(UPDATEDATIM) AS LAST_PRICECHANGE_UPDATEDATIM

    FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERPRICECHANGE
    GROUP BY
        JOBNUMBER,
        ESTIMATENUMBER
)

SELECT
    oh.*,

    pc.PRICECHANGE_TOTALPRICE,
    pc.PRICECHANGE_PRICEADJUSTMENT,
    pc.PRICECHANGE_ROW_COUNT,
    pc.FIRST_PRICECHANGE_ENTRYDATE,
    pc.LAST_PRICECHANGE_ENTRYDATE,
    pc.FIRST_PRICECHANGE_CREATEDATIM,
    pc.LAST_PRICECHANGE_CREATEDATIM,
    pc.FIRST_PRICECHANGE_UPDATEDATIM,
    pc.LAST_PRICECHANGE_UPDATEDATIM

FROM DATA_VALIDATION.MART_REVENUE.V_ORDERHEADER_ANALYTICS oh
LEFT JOIN price_change pc
    ON oh.JOBNUMBER = pc.JOBNUMBER
   AND oh.ESTIMATENUMBER = pc.ESTIMATENUMBER;;
