create or replace view V_ORDERCOMPONENT_WITH_TEXT_GROUPED(
	JOBNUMBER,
	USERDEFINED6,
	ENTRYDATE,
	DUEDATE,
	DELIVERYDATE,
	PROOFDUEDATE,
	PROOFDELIVERYDATE,
	CREATEDATIM,
	UPDATEDATIM,
	COMPONENTNUMBER,
	COMPONENTTYPE,
	COMPONENT_TYPE,
	FINGOODCODE,
	USEQUANTITYTABLE,
	DISCOUNT,
	MANUALPRESSOUTS,
	ESTIMATENUMBER,
	CHARGEZERO,
	DONTCALCULATE,
	COMPONENTPLANNED,
	MANUALPRICEMETHOD,
	MANUALPRICEOVERRIDE,
	USERDEFINED2,
	USERDEFINED4,
	ID,
	HEADERID,
	TAXJURISDICTION,
	SUM_QUANTITYORDERED,
	SUM_PRODUCTIONMARKUP,
	SUM_MATERIALMARKUP,
	SUM_STOCKMARKUP,
	SUM_TOTALSELLPRICE,
	SUM_DISCOUNTDOLLARS,
	ROW_COUNT,
	TEXT_COMPONENTNUMBER,
	TEXT_ESTIMATENUMBER,
	COMPONENTID,
	TEXT_HEADERID,
	TEXT_CREATEDATIM,
	TEXT_UPDATEDATIM,
	TEXT_ROW_COUNT
) as
WITH order_component AS (
    SELECT *
    FROM DATA_VALIDATION.MART_REVENUE.V_ORDERCOMPONENT_GROUPED
),

component_text AS (
    SELECT
        JOBNUMBER,
        COMPONENTNUMBER AS TEXT_COMPONENTNUMBER,
        ESTIMATENUMBER AS TEXT_ESTIMATENUMBER,
        COMPONENTID,
        HEADERID AS TEXT_HEADERID,
        CREATEDATIM AS TEXT_CREATEDATIM,
        UPDATEDATIM AS TEXT_UPDATEDATIM,
        COUNT(*) AS TEXT_ROW_COUNT
    FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERCOMPONENTTEXT
    GROUP BY
        JOBNUMBER,
        COMPONENTNUMBER,
        ESTIMATENUMBER,
        COMPONENTID,
        HEADERID,
        CREATEDATIM,
        UPDATEDATIM
)

SELECT
    oc.*,

    ct.TEXT_COMPONENTNUMBER,
    ct.TEXT_ESTIMATENUMBER,
    ct.COMPONENTID,
    ct.TEXT_HEADERID,
    ct.TEXT_CREATEDATIM,
    ct.TEXT_UPDATEDATIM,
    ct.TEXT_ROW_COUNT

FROM order_component oc
LEFT JOIN component_text ct
    ON oc.JOBNUMBER = ct.JOBNUMBER;;
