create or replace view V_ORDERUNITCOST_ANALYTICS(
	JOBNUMBER,
	ESTIMATENUMBER,
	COMPONENTNUMBER,
	GROUPNO,
	ITEMNUMBER,
	PARTNUMBER,
	PROCESSID,
	ENTRYDATE,
	CREATEDATIM,
	UPDATEDATIM,
	TOTAL_QUANTITY,
	TOTAL_UNITCOST,
	TOTAL_MINIMUMCOST,
	TOTAL_MARKUP,
	TOTAL_OVERS,
	TOTAL_UNITPRICEOVERRIDE,
	TOTAL_QUANTITYOVERRIDE,
	ROW_COUNT
) as
SELECT
    JOBNUMBER,
    ESTIMATENUMBER,
    COMPONENTNUMBER,
    GROUPNO,
    ITEMNUMBER,
    PARTNUMBER,
    PROCESSID,

    MIN(ENTRYDATE) AS ENTRYDATE,
    MIN(CREATEDATIM) AS CREATEDATIM,
    MAX(UPDATEDATIM) AS UPDATEDATIM,

    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(UNITCOST) AS TOTAL_UNITCOST,
    SUM(MINIMUMCOST) AS TOTAL_MINIMUMCOST,
    SUM(MARKUP) AS TOTAL_MARKUP,
    SUM(OVERS) AS TOTAL_OVERS,
    SUM(UNITPRICEOVERRIDE) AS TOTAL_UNITPRICEOVERRIDE,
    SUM(QUANTITYOVERRIDE) AS TOTAL_QUANTITYOVERRIDE,

    COUNT(*) AS ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERUNITCOST
GROUP BY
    JOBNUMBER,
    ESTIMATENUMBER,
    COMPONENTNUMBER,
    GROUPNO,
    ITEMNUMBER,
    PARTNUMBER,
    PROCESSID;;
