create or replace view V_ORDERCOMBINEQUOTE_JOB_ESTIMATE_TOTALS(
	JOBNUMBER,
	ESTIMATENUMBER,
	TOTALPRICE,
	ADDCOLORPRICE,
	ADDCOLORMATPRICE,
	ADDMPRICE,
	TAXAMOUNT,
	DISCOUNTAMOUNT,
	QUANTITY,
	CQUANTITY,
	ROW_COUNT
) as
SELECT
    JOBNUMBER,
    ESTIMATENUMBER,

    SUM(
        COALESCE(TOTALPRICE1, 0) +
        COALESCE(TOTALPRICE2, 0) +
        COALESCE(TOTALPRICE3, 0) +
        COALESCE(TOTALPRICE4, 0) +
        COALESCE(TOTALPRICE5, 0) +
        COALESCE(TOTALPRICE6, 0)
    ) AS TOTALPRICE,

    SUM(
        COALESCE(ADDCOLORPRICE1, 0) +
        COALESCE(ADDCOLORPRICE2, 0) +
        COALESCE(ADDCOLORPRICE3, 0) +
        COALESCE(ADDCOLORPRICE4, 0) +
        COALESCE(ADDCOLORPRICE5, 0) +
        COALESCE(ADDCOLORPRICE6, 0)
    ) AS ADDCOLORPRICE,

    SUM(
        COALESCE(ADDCOLORMATPRICE1, 0) +
        COALESCE(ADDCOLORMATPRICE2, 0) +
        COALESCE(ADDCOLORMATPRICE3, 0) +
        COALESCE(ADDCOLORMATPRICE4, 0) +
        COALESCE(ADDCOLORMATPRICE5, 0) +
        COALESCE(ADDCOLORMATPRICE6, 0)
    ) AS ADDCOLORMATPRICE,

    SUM(
        COALESCE(ADDMPRICE1, 0) +
        COALESCE(ADDMPRICE2, 0) +
        COALESCE(ADDMPRICE3, 0) +
        COALESCE(ADDMPRICE4, 0) +
        COALESCE(ADDMPRICE5, 0) +
        COALESCE(ADDMPRICE6, 0)
    ) AS ADDMPRICE,

    SUM(
        COALESCE(TAXAMOUNT1, 0) +
        COALESCE(TAXAMOUNT2, 0) +
        COALESCE(TAXAMOUNT3, 0) +
        COALESCE(TAXAMOUNT4, 0) +
        COALESCE(TAXAMOUNT5, 0) +
        COALESCE(TAXAMOUNT6, 0)
    ) AS TAXAMOUNT,

    SUM(
        COALESCE(DISCOUNTAMOUNT1, 0) +
        COALESCE(DISCOUNTAMOUNT2, 0) +
        COALESCE(DISCOUNTAMOUNT3, 0) +
        COALESCE(DISCOUNTAMOUNT4, 0) +
        COALESCE(DISCOUNTAMOUNT5, 0) +
        COALESCE(DISCOUNTAMOUNT6, 0)
    ) AS DISCOUNTAMOUNT,

    SUM(
        COALESCE(QUANTITY1, 0) +
        COALESCE(QUANTITY2, 0) +
        COALESCE(QUANTITY3, 0) +
        COALESCE(QUANTITY4, 0) +
        COALESCE(QUANTITY5, 0) +
        COALESCE(QUANTITY6, 0)
    ) AS QUANTITY,

    SUM(
        COALESCE(CQUANTITY1, 0) +
        COALESCE(CQUANTITY2, 0) +
        COALESCE(CQUANTITY3, 0) +
        COALESCE(CQUANTITY4, 0) +
        COALESCE(CQUANTITY5, 0) +
        COALESCE(CQUANTITY6, 0)
    ) AS CQUANTITY,

    COUNT(*) AS ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERCOMBINEQUOTE
GROUP BY
    JOBNUMBER,
    ESTIMATENUMBER
ORDER BY
    JOBNUMBER,
    ESTIMATENUMBER;
;;
