create or replace view V_ORDERUNITCOST_COMPONENT_ANALYTICS(
	JOBNUMBER,
	ESTIMATENUMBER,
	COMPONENTNUMBER,
	TOTAL_QUANTITY,
	TOTAL_UNITCOST,
	TOTAL_MINIMUMCOST,
	TOTAL_MARKUP,
	TOTAL_OVERS,
	TOTAL_UNITPRICEOVERRIDE,
	TOTAL_QUANTITYOVERRIDE,
	PROCESS_COUNT,
	ROW_COUNT,
	FIRST_CREATEDATIM,
	LAST_UPDATEDATIM
) as
SELECT
    JOBNUMBER,
    ESTIMATENUMBER,
    COMPONENTNUMBER,

    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(UNITCOST) AS TOTAL_UNITCOST,
    SUM(MINIMUMCOST) AS TOTAL_MINIMUMCOST,
    SUM(MARKUP) AS TOTAL_MARKUP,
    SUM(OVERS) AS TOTAL_OVERS,
    SUM(UNITPRICEOVERRIDE) AS TOTAL_UNITPRICEOVERRIDE,
    SUM(QUANTITYOVERRIDE) AS TOTAL_QUANTITYOVERRIDE,

    COUNT(DISTINCT PROCESSID) AS PROCESS_COUNT,
    COUNT(*) AS ROW_COUNT,

    MIN(CREATEDATIM) AS FIRST_CREATEDATIM,
    MAX(UPDATEDATIM) AS LAST_UPDATEDATIM

FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERUNITCOST
GROUP BY
    JOBNUMBER,
    ESTIMATENUMBER,
    COMPONENTNUMBER;;
