create or replace view V_ORDER_MART(
	JOBNUMBER,
	ESTIMATENUMBER,
	FORMNUMBER,
	CUSTACCOUNT,
	CUSTNAME,
	CUSTSTATE,
	PLANTID,
	ORDERDATE,
	DUEDATE,
	DELIVERYDATE,
	ORDERTYPE,
	PONUMBER,
	PODATE,
	CREATEDATIM,
	UPDATEDATIM,
	JOBSTATUS,
	USERDEFINED1,
	USERDEFINED4,
	USERDEFINED5,
	ESTIMATESTATUS,
	SUM_PREPAYMENT,
	SUM_TOTALCOMPONENTS,
	SUM_TOTALCOMPONENTSQTYCALCULATED,
	SUM_TOTALSELLPRICE,
	SUM_ORDERSELLPRICE,
	SUM_INVOICESELLPRICE,
	SUM_INVOICEDFREIGHTPRICE,
	SUM_CALCULATEDTOTALPRICE,
	SUM_DISCOUNT,
	ROW_COUNT,
	ORDERTOTALS_TOTAL_QUANTITY,
	ORDERTOTALS_TOTALPRICE,
	ORDERTOTALS_ADDCOLORPRICE,
	ORDERTOTALS_ADDCOLORMATPRICE,
	ORDERTOTALS_GRIDPRICE,
	ORDERTOTALS_COMMISSIONAMOUNT,
	ORDERTOTALS_ADDMPRICE,
	ORDERTOTALS_TAXAMOUNTA,
	ORDERTOTALS_TAXAMOUNTB,
	ORDERTOTALS_TAXAMOUNTC,
	ORDERTOTALS_TAXAMOUNTD,
	ORDERTOTALS_DISCOUNTAMOUNT,
	ORDERTOTALS_QUANTITY_BREAK_COUNT,
	PRICECHANGE_TOTALPRICE,
	PRICECHANGE_PRICEADJUSTMENT,
	PRICECHANGE_ROW_COUNT,
	COMBINEQUOTE_TOTALPRICE,
	COMBINEQUOTE_ADDCOLORPRICE,
	COMBINEQUOTE_ADDCOLORMATPRICE,
	COMBINEQUOTE_ADDMPRICE,
	COMBINEQUOTE_TAXAMOUNT,
	COMBINEQUOTE_DISCOUNTAMOUNT,
	COMBINEQUOTE_QUANTITY,
	COMBINEQUOTE_CQUANTITY,
	COMBINEQUOTE_ROW_COUNT,
	UDFIELD_COUNT,
	DISTINCT_FIELDLABEL_COUNT,
	DISTINCT_SECTION_COUNT
) as
SELECT
    oh.*,

    ot.TOTAL_QUANTITY AS ORDERTOTALS_TOTAL_QUANTITY,
    ot.TOTAL_TOTALPRICE AS ORDERTOTALS_TOTALPRICE,
    ot.TOTAL_ADDCOLORPRICE AS ORDERTOTALS_ADDCOLORPRICE,
    ot.TOTAL_ADDCOLORMATPRICE AS ORDERTOTALS_ADDCOLORMATPRICE,
    ot.TOTAL_GRIDPRICE AS ORDERTOTALS_GRIDPRICE,
    ot.TOTAL_COMMISSIONAMOUNT AS ORDERTOTALS_COMMISSIONAMOUNT,
    ot.TOTAL_ADDMPRICE AS ORDERTOTALS_ADDMPRICE,
    ot.TOTAL_TAXAMOUNTA AS ORDERTOTALS_TAXAMOUNTA,
    ot.TOTAL_TAXAMOUNTB AS ORDERTOTALS_TAXAMOUNTB,
    ot.TOTAL_TAXAMOUNTC AS ORDERTOTALS_TAXAMOUNTC,
    ot.TOTAL_TAXAMOUNTD AS ORDERTOTALS_TAXAMOUNTD,
    ot.TOTAL_DISCOUNTAMOUNT AS ORDERTOTALS_DISCOUNTAMOUNT,
    ot.QUANTITY_BREAK_COUNT AS ORDERTOTALS_QUANTITY_BREAK_COUNT,

    pc.PRICECHANGE_TOTALPRICE,
    pc.PRICECHANGE_PRICEADJUSTMENT,
    pc.PRICECHANGE_ROW_COUNT,

    cq.TOTALPRICE AS COMBINEQUOTE_TOTALPRICE,
    cq.ADDCOLORPRICE AS COMBINEQUOTE_ADDCOLORPRICE,
    cq.ADDCOLORMATPRICE AS COMBINEQUOTE_ADDCOLORMATPRICE,
    cq.ADDMPRICE AS COMBINEQUOTE_ADDMPRICE,
    cq.TAXAMOUNT AS COMBINEQUOTE_TAXAMOUNT,
    cq.DISCOUNTAMOUNT AS COMBINEQUOTE_DISCOUNTAMOUNT,
    cq.QUANTITY AS COMBINEQUOTE_QUANTITY,
    cq.CQUANTITY AS COMBINEQUOTE_CQUANTITY,
    cq.ROW_COUNT AS COMBINEQUOTE_ROW_COUNT,

    udf.UDFIELD_COUNT,
    udf.DISTINCT_FIELDLABEL_COUNT,
    udf.DISTINCT_SECTION_COUNT

FROM DATA_VALIDATION.MART_REVENUE.V_ORDERHEADER_ANALYTICS oh

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_ORDERTOTALS_JOB_ANALYTICS ot
    ON oh.JOBNUMBER = ot.JOBNUMBER
   AND oh.ESTIMATENUMBER = ot.ESTIMATENUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_ORDERHEADER_WITH_PRICE_CHANGES pc
    ON oh.JOBNUMBER = pc.JOBNUMBER
   AND oh.ESTIMATENUMBER = pc.ESTIMATENUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_ORDERCOMBINEQUOTE_JOB_ESTIMATE_TOTALS cq
    ON oh.JOBNUMBER = cq.JOBNUMBER
   AND oh.ESTIMATENUMBER = cq.ESTIMATENUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_ORDERUDFIELDS_JOB_ANALYTICS udf
    ON oh.JOBNUMBER = udf.JOBNUMBER
   AND oh.ESTIMATENUMBER = udf.ESTIMATENUMBER;;
