create or replace view V_ORDERUDFIELDS_ANALYTICS(
	JOBNUMBER,
	ESTIMATENUMBER,
	COMPONENTNUMBER,
	COMPONENTID,
	FIELDLABEL,
	FIELDVALUE,
	FIELDSEQUENCENUMBER,
	SECTION,
	FIRST_CREATEDATIM,
	LAST_UPDATEDATIM,
	ROW_COUNT
) as
SELECT
    JOBNUMBER,
    ESTIMATENUMBER,
    COMPONENTNUMBER,
    COMPONENTID,
    FIELDLABEL,
    FIELDVALUE,
    FIELDSEQUENCENUMBER,
    SECTION,

    MIN(CREATEDATIM) AS FIRST_CREATEDATIM,
    MAX(UPDATEDATIM) AS LAST_UPDATEDATIM,

    COUNT(*) AS ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERUDFIELDS
GROUP BY
    JOBNUMBER,
    ESTIMATENUMBER,
    COMPONENTNUMBER,
    COMPONENTID,
    FIELDLABEL,
    FIELDVALUE,
    FIELDSEQUENCENUMBER,
    SECTION;;
