create or replace view V_ORDER_COMPONENT_ANALYTICS(
	JOBNUMBER,
	ESTIMATENUMBER,
	PLANTID,
	CUSTACCOUNT,
	CUSTNAME,
	ORDERDATE_RAW,
	ORDER_DATE,
	DUEDATE_RAW,
	DUE_DATE,
	JOBSTATUS,
	ORDER_STATUS_CODE,
	SALESREPCODE,
	HEADER_TOTAL_SELL_PRICE,
	ORDERSELLPRICE,
	INVOICESELLPRICE,
	COMPONENTNUMBER,
	COMPONENT_DESCRIPTION,
	COMPONENTTYPE,
	QUANTITYORDERED,
	COMPONENT_TOTAL_SELL_PRICE,
	PRODUCTIONCOST,
	MATERIALCOST,
	OSCOST,
	PRODUCTIONPRICE,
	MATERIALPRICE,
	OSPRICE,
	TOTAL_COST,
	TOTAL_PRICE,
	AR_TRANSACTION_COUNT,
	AR_NETVAL,
	AR_TOTALVAL,
	AR_COSTVAL,
	SHIPMENT_COUNT,
	FIRST_SCHEDULED_SHIP_DATE_RAW,
	LAST_SCHEDULED_SHIP_DATE_RAW,
	FIRST_SCHEDULED_SHIP_DATE,
	LAST_SCHEDULED_SHIP_DATE,
	SCHEDULED_SHIP_QUANTITY,
	HAS_SHIPPED_FLAG,
	PROCESS_ROW_COUNT,
	PROCESS_COUNT,
	PROCESS_CODE_COUNT,
	MATERIAL_CODE_COUNT,
	PROCESS_VENDOR_COUNT,
	PROCESS_PRODUCTION_QUANTITY,
	PROCESS_FIXED_COST,
	PROCESS_FIXED_QUANTITY,
	PROCESS_SHEET_SPOILAGE,
	PROCESS_SETUP_SPOILAGE,
	PROCESS_ONE_SIDED_SHEETS,
	PROCESS_TWO_SIDED_SHEETS,
	PROCESS_BLANK_SHEETS,
	HAS_ADDITIONAL_CHARGE_FLAG,
	HAS_RUSH_CHARGE_FLAG,
	DIM_CUSTNAME,
	CUSTCITY,
	CUSTSTATE,
	CUSTCOUNTRY,
	CUSTEMAIL,
	CUSTOMER_SALESREPCODE,
	CUSTOMER_CSR,
	SALESREP_CSR,
	SALESREP_PLANTID,
	PLANT_JOB_COUNT,
	PLANT_CUSTOMER_COUNT,
	PLANT_FIRST_ORDER_DATE,
	PLANT_LAST_ORDER_DATE
) as
SELECT
    f.*,

    c.CUSTNAME AS DIM_CUSTNAME,
    c.CUSTCITY,
    c.CUSTSTATE,
    c.CUSTCOUNTRY,
    c.CUSTEMAIL,

    c.SALESREPCODE AS CUSTOMER_SALESREPCODE,
    c.CSR AS CUSTOMER_CSR,

    sr.CSR AS SALESREP_CSR,
    sr.PLANTID AS SALESREP_PLANTID,

    p.JOB_COUNT AS PLANT_JOB_COUNT,
    p.CUSTOMER_COUNT AS PLANT_CUSTOMER_COUNT,
    p.FIRST_ORDER_DATE AS PLANT_FIRST_ORDER_DATE,
    p.LAST_ORDER_DATE AS PLANT_LAST_ORDER_DATE

FROM DATA_VALIDATION.MART_REVENUE.FACT_ORDER_COMPONENT f

LEFT JOIN DATA_VALIDATION.MART_REVENUE.DIM_CUSTOMER c
    ON f.CUSTACCOUNT = c.CUSTACCOUNT

LEFT JOIN DATA_VALIDATION.MART_REVENUE.DIM_SALESREP sr
    ON f.SALESREPCODE = sr.SALESREPCODE

LEFT JOIN DATA_VALIDATION.MART_REVENUE.DIM_PLANT p
    ON f.PLANTID = p.PLANTID;;
