create or replace view V_ORDERTOTALS_JOB_ANALYTICS(
	JOBNUMBER,
	ESTIMATENUMBER,
	TOTAL_QUANTITY,
	TOTAL_TOTALPRICE,
	TOTAL_ADDCOLORPRICE,
	TOTAL_ADDCOLORMATPRICE,
	TOTAL_GRIDPRICE,
	TOTAL_COMMISSIONAMOUNT,
	TOTAL_ADDMPRICE,
	TOTAL_TAXAMOUNTA,
	TOTAL_TAXAMOUNTB,
	TOTAL_TAXAMOUNTC,
	TOTAL_TAXAMOUNTD,
	TOTAL_DISCOUNTAMOUNT,
	QUANTITY_BREAK_COUNT
) as
SELECT
    JOBNUMBER,
    ESTIMATENUMBER,

    SUM(QUANTITY) AS TOTAL_QUANTITY,

    SUM(TOTALPRICE) AS TOTAL_TOTALPRICE,
    SUM(ADDCOLORPRICE) AS TOTAL_ADDCOLORPRICE,
    SUM(ADDCOLORMATPRICE) AS TOTAL_ADDCOLORMATPRICE,
    SUM(GRIDPRICE) AS TOTAL_GRIDPRICE,
    SUM(COMMISSIONAMOUNT) AS TOTAL_COMMISSIONAMOUNT,
    SUM(ADDMPRICE) AS TOTAL_ADDMPRICE,

    SUM(TAXAMOUNTA) AS TOTAL_TAXAMOUNTA,
    SUM(TAXAMOUNTB) AS TOTAL_TAXAMOUNTB,
    SUM(TAXAMOUNTC) AS TOTAL_TAXAMOUNTC,
    SUM(TAXAMOUNTD) AS TOTAL_TAXAMOUNTD,

    SUM(DISCOUNTAMOUNT) AS TOTAL_DISCOUNTAMOUNT,

    COUNT(*) AS QUANTITY_BREAK_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERTOTALS
GROUP BY
    JOBNUMBER,
    ESTIMATENUMBER;;
