create or replace view V_ORDERUDFIELDS_JOB_ANALYTICS(
	JOBNUMBER,
	ESTIMATENUMBER,
	UDFIELD_COUNT,
	DISTINCT_FIELDLABEL_COUNT,
	DISTINCT_SECTION_COUNT,
	FIRST_UDFIELD_CREATEDATIM,
	LAST_UDFIELD_UPDATEDATIM
) as
SELECT
    JOBNUMBER,
    ESTIMATENUMBER,

    COUNT(*) AS UDFIELD_COUNT,
    COUNT(DISTINCT FIELDLABEL) AS DISTINCT_FIELDLABEL_COUNT,
    COUNT(DISTINCT SECTION) AS DISTINCT_SECTION_COUNT,

    MIN(CREATEDATIM) AS FIRST_UDFIELD_CREATEDATIM,
    MAX(UPDATEDATIM) AS LAST_UDFIELD_UPDATEDATIM

FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERUDFIELDS
GROUP BY
    JOBNUMBER,
    ESTIMATENUMBER;;
