create or replace view V_PLANT_PERFORMANCE(
	PLANTID,
	CUSTOMER_COUNT,
	ACTIVE_MONTHS,
	JOB_COUNT,
	COMPONENT_COUNT,
	COMPONENT_REVENUE,
	TOTAL_COST,
	ESTIMATED_MARGIN
) as
SELECT
    PLANTID,

    COUNT(DISTINCT CUSTACCOUNT) AS CUSTOMER_COUNT,
    COUNT(DISTINCT ORDER_MONTH) AS ACTIVE_MONTHS,

    SUM(JOB_COUNT) AS JOB_COUNT,
    SUM(COMPONENT_COUNT) AS COMPONENT_COUNT,

    SUM(COMPONENT_TOTAL_SELL_PRICE) AS COMPONENT_REVENUE,
    SUM(TOTAL_COST) AS TOTAL_COST,
    SUM(COMPONENT_TOTAL_SELL_PRICE) - SUM(TOTAL_COST) AS ESTIMATED_MARGIN

FROM DATA_VALIDATION.MART_REVENUE.MONTHLY_REVENUE_SUMMARY
GROUP BY PLANTID;;
