create or replace view V_POIMAGE_ANALYTICS(
	PONUMBER,
	IMAGEID,
	IMAGETYPECODE,
	FIRST_CREATEDATIM,
	TOTAL_FILESIZE,
	IMAGE_ROW_COUNT
) as
SELECT
    PONUMBER,
    IMAGEID,
    IMAGETYPECODE,

    MIN(CREATEDATIM) AS FIRST_CREATEDATIM,

    SUM(FILESIZE) AS TOTAL_FILESIZE,
    COUNT(*) AS IMAGE_ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.POIMAGE
GROUP BY
    PONUMBER,
    IMAGEID,
    IMAGETYPECODE;;
