create or replace view V_PODROPSHIP_ANALYTICS(
	PONUMBER,
	DROPSHIPNO,
	SHIPACCOUNT,
	SHIPNAME,
	SHIPCITY,
	SHIPSTATE,
	SHIPZIP,
	SHIPCOUNTRY,
	SHIPCONTACTID,
	ENTRY_DATE,
	FIRST_CREATEDATIM,
	LAST_UPDATEDATIM,
	ROW_COUNT
) as
SELECT
    PONUMBER,
    DROPSHIPNO,
    SHIPACCOUNT,
    SHIPNAME,
    SHIPCITY,
    SHIPSTATE,
    SHIPZIP,
    SHIPCOUNTRY,
    SHIPCONTACTID,

    MIN(ENTRYDATE) AS ENTRY_DATE,
    MIN(CREATEDATIM) AS FIRST_CREATEDATIM,
    MAX(UPDATEDATIM) AS LAST_UPDATEDATIM,

    COUNT(*) AS ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.PODROPSHIP
GROUP BY
    PONUMBER,
    DROPSHIPNO,
    SHIPACCOUNT,
    SHIPNAME,
    SHIPCITY,
    SHIPSTATE,
    SHIPZIP,
    SHIPCOUNTRY,
    SHIPCONTACTID;;
