create or replace view V_POHEADER_ANALYTICS(
	PONUMBER,
	VENDORID,
	POAGENT,
	POSTATUS,
	PLANTID,
	CUSTACCOUNT,
	COMPANYID,
	CURRENCYCODE,
	SECONDARYVENDORID,
	ISSUE_DATE,
	INVOICE_DATE,
	ENTRY_DATE,
	POSTING_DATE,
	FIRST_CREATEDATIM,
	LAST_UPDATEDATIM,
	TOTAL_POSTAGEREQUEST,
	TOTAL_EXCHANGERATE,
	ROW_COUNT
) as
SELECT
    PONUMBER,
    VENDORID,
    POAGENT,
    POSTATUS,
    PLANTID,
    CUSTACCOUNT,
    COMPANYID,
    CURRENCYCODE,
    SECONDARYVENDORID,

    MIN(ISSUEDATE) AS ISSUE_DATE,
    MIN(INVOICEDATE) AS INVOICE_DATE,
    MIN(ENTRYDATE) AS ENTRY_DATE,
    MIN(POSTINGDATE) AS POSTING_DATE,
    MIN(CREATEDATIM) AS FIRST_CREATEDATIM,
    MAX(UPDATEDATIM) AS LAST_UPDATEDATIM,

    SUM(POSTAGEREQUEST) AS TOTAL_POSTAGEREQUEST,
    SUM(EXCHANGERATE) AS TOTAL_EXCHANGERATE,

    COUNT(*) AS ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.POHEADER
GROUP BY
    PONUMBER,
    VENDORID,
    POAGENT,
    POSTATUS,
    PLANTID,
    CUSTACCOUNT,
    COMPANYID,
    CURRENCYCODE,
    SECONDARYVENDORID;;
