create or replace view V_PROCESS_MART(
	JOBNUMBER,
	COMPONENTNUMBER,
	GLACCOUNT,
	GLCOGACCOUNT,
	GROUPNO,
	ITEMNUMBER,
	PARTNUMBER,
	PROCESSCODE,
	MATERIALCODE,
	VENDORID,
	VENDORNAME,
	VENDORPRODUCTID,
	DIFFICULTY,
	CHANGEORDER,
	ENTRYDATE,
	CHANGEDATE,
	CREATEDATIM,
	UPDATEDATIM,
	APPROVALCODE,
	DUEDATE,
	COSTINGMETHOD,
	ESTIMATENUMBER,
	CHANGEORDERID,
	FORMPARTNUMBER,
	USERDEFINED1,
	USERDEFINED2,
	USERDEFINED3,
	USERDEFINED4,
	USERDEFINED5,
	DONTINVOICEITEM,
	RUSHCHARGE,
	MULTIPLYBYPARTS,
	ID,
	PROCESSID,
	COMPONENTID,
	SUM_UNITSPERCYCLE,
	SUM_FIXEDMARKUP,
	SUM_FIXEDCOST,
	SUM_FIXEDQUANTITY,
	SUM_ADDITIONALCHARGE,
	SUM_FIXEDUNITCOST,
	SUM_DISCOUNT,
	SUM_PRODUCTIONQUANTITY,
	SUM_ADDTOTEMPLATEPRICE,
	SUM_UNITCOSTOVERRIDE,
	SUM_USERATEOVERRIDEASPRICE,
	SUM_OVERRIDEUNITSPERCYCLE,
	ROW_COUNT,
	ORDERVALUE_PRODUCTIONQUANTITY,
	ORDERVALUE_MATERIALQUANTITY,
	ORDERVALUE_PRODUCTIONMINUTES,
	ORDERVALUE_PRODUCTIONCOST,
	ORDERVALUE_MATERIALCOST,
	ORDERVALUE_OSCOST,
	ORDERVALUE_PRODUCTIONPRICE,
	ORDERVALUE_MATERIALPRICE,
	ORDERVALUE_OSPRICE,
	ORDERVALUE_UNITCOST,
	ORDERVALUE_ROYALTYAMOUNT,
	ORDERVALUE_ROW_COUNT,
	SCHEDULE_ESTIMATEDHOURS,
	SCHEDULE_SCHEDULEDHOURS,
	SCHEDULE_SCHEDULEDDAYS,
	SCHEDULE_BUFFERHOURS,
	SCHEDULE_COMPLETED,
	SCHEDULE_STARTDATEGAP,
	SCHEDULE_ROW_COUNT,
	PRODUCTION_PERCENTAGE,
	PRODUCTION_JOB_QUANTITY,
	PRODUCTION_QUANTITY,
	PRODUCTION_ELAPSEDTIME,
	PRODUCTION_UNITCOST,
	PRODUCTION_AICOST,
	PRODUCTION_DMCOST,
	PRODUCTION_WAGECOST,
	PRODUCTION_WIPCOST,
	PRODUCTION_INLINEOPCOST,
	PRODUCTION_ROW_COUNT
) as
SELECT
    op.*,

    ov.TOTAL_PRODUCTIONQUANTITY AS ORDERVALUE_PRODUCTIONQUANTITY,
    ov.TOTAL_MATERIALQUANTITY AS ORDERVALUE_MATERIALQUANTITY,
    ov.TOTAL_PRODUCTIONMINUTES AS ORDERVALUE_PRODUCTIONMINUTES,
    ov.TOTAL_PRODUCTIONCOST AS ORDERVALUE_PRODUCTIONCOST,
    ov.TOTAL_MATERIALCOST AS ORDERVALUE_MATERIALCOST,
    ov.TOTAL_OSCOST AS ORDERVALUE_OSCOST,
    ov.TOTAL_PRODUCTIONPRICE AS ORDERVALUE_PRODUCTIONPRICE,
    ov.TOTAL_MATERIALPRICE AS ORDERVALUE_MATERIALPRICE,
    ov.TOTAL_OSPRICE AS ORDERVALUE_OSPRICE,
    ov.TOTAL_UNITCOST AS ORDERVALUE_UNITCOST,
    ov.TOTAL_ROYALTYAMOUNT AS ORDERVALUE_ROYALTYAMOUNT,
    ov.ROW_COUNT AS ORDERVALUE_ROW_COUNT,

    ps.SUM_ESTIMATEDHOURS AS SCHEDULE_ESTIMATEDHOURS,
    ps.SUM_SCHEDULEDHOURS AS SCHEDULE_SCHEDULEDHOURS,
    ps.SUM_SCHEDULEDDAYS AS SCHEDULE_SCHEDULEDDAYS,
    ps.SUM_BUFFERHOURS AS SCHEDULE_BUFFERHOURS,
    ps.SUM_COMPLETED AS SCHEDULE_COMPLETED,
    ps.SUM_STARTDATEGAP AS SCHEDULE_STARTDATEGAP,
    ps.ROW_COUNT AS SCHEDULE_ROW_COUNT,

    pj.SUM_PERCENTAGE AS PRODUCTION_PERCENTAGE,
    pj.SUM_JOB_QUANTITY AS PRODUCTION_JOB_QUANTITY,
    pj.SUM_QUANTITY AS PRODUCTION_QUANTITY,
    pj.SUM_ELAPSEDTIME AS PRODUCTION_ELAPSEDTIME,
    pj.SUM_UNITCOST AS PRODUCTION_UNITCOST,
    pj.SUM_AICOST AS PRODUCTION_AICOST,
    pj.SUM_DMCOST AS PRODUCTION_DMCOST,
    pj.SUM_WAGECOST AS PRODUCTION_WAGECOST,
    pj.SUM_WIPCOST AS PRODUCTION_WIPCOST,
    pj.SUM_INLINEOPCOST AS PRODUCTION_INLINEOPCOST,
    pj.ROW_COUNT AS PRODUCTION_ROW_COUNT

FROM DATA_VALIDATION.MART_REVENUE.V_ORDERPROCESS_GROUPED op

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_ORDERVALUE_ANALYTICS ov
    ON op.JOBNUMBER = ov.JOBNUMBER
   AND op.ESTIMATENUMBER = ov.ESTIMATENUMBER
   AND op.COMPONENTNUMBER = ov.COMPONENTNUMBER
   AND op.PROCESSID = ov.PROCESSID

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_PROCESSSCHEDULE_GROUPED ps
    ON op.JOBNUMBER = ps.JOBNUMBER
   AND op.COMPONENTNUMBER = ps.COMPONENTNUMBER
   AND op.PROCESSCODE = ps.PROCESSCODE

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_PRODUCTION_JOB_GROUPED pj
    ON op.JOBNUMBER = pj.JOBNUMBER
   AND op.COMPONENTNUMBER = pj.COMPONENTNUMBER
   AND op.PROCESSCODE = pj.PROCESSCODE;;
