create or replace view V_PRODUCTION_MART(
	JOBNUMBER,
	COMPONENTNUMBER,
	PROCESSCODE,
	PRODUCTION_PERCENTAGE,
	PRODUCTION_JOB_QUANTITY,
	PRODUCTION_QUANTITY,
	PRODUCTION_ELAPSEDTIME,
	PRODUCTION_UNITCOST,
	PRODUCTION_AICOST,
	PRODUCTION_DMCOST,
	PRODUCTION_TOTALCOPIES,
	PRODUCTION_GOODCOPIES,
	PRODUCTION_ACTUALWASTE,
	PRODUCTION_BADQUANTITY,
	PRODUCTION_WAGECOST,
	PRODUCTION_WIPCOST,
	PRODUCTION_INLINEOPCOST,
	PRODUCTION_ROW_COUNT,
	SCHEDULE_ESTIMATEDHOURS,
	SCHEDULE_SCHEDULEDHOURS,
	SCHEDULE_SCHEDULEDDAYS,
	SCHEDULE_BUFFERHOURS,
	SCHEDULE_COMPLETED,
	SCHEDULE_STARTDATEGAP,
	SCHEDULE_ROW_COUNT
) as
SELECT
    pj.JOBNUMBER,
    pj.COMPONENTNUMBER,
    pj.PROCESSCODE,

    SUM(pj.SUM_PERCENTAGE) AS PRODUCTION_PERCENTAGE,
    SUM(pj.SUM_JOB_QUANTITY) AS PRODUCTION_JOB_QUANTITY,
    SUM(pj.SUM_QUANTITY) AS PRODUCTION_QUANTITY,
    SUM(pj.SUM_ELAPSEDTIME) AS PRODUCTION_ELAPSEDTIME,
    SUM(pj.SUM_UNITCOST) AS PRODUCTION_UNITCOST,
    SUM(pj.SUM_AICOST) AS PRODUCTION_AICOST,
    SUM(pj.SUM_DMCOST) AS PRODUCTION_DMCOST,
    SUM(pj.SUM_TOTALCOPIES) AS PRODUCTION_TOTALCOPIES,
    SUM(pj.SUM_GOODCOPIES) AS PRODUCTION_GOODCOPIES,
    SUM(pj.SUM_ACTUALWASTE) AS PRODUCTION_ACTUALWASTE,
    SUM(pj.SUM_BADQUANTITY) AS PRODUCTION_BADQUANTITY,
    SUM(pj.SUM_WAGECOST) AS PRODUCTION_WAGECOST,
    SUM(pj.SUM_WIPCOST) AS PRODUCTION_WIPCOST,
    SUM(pj.SUM_INLINEOPCOST) AS PRODUCTION_INLINEOPCOST,
    SUM(pj.ROW_COUNT) AS PRODUCTION_ROW_COUNT,

    SUM(ps.SUM_ESTIMATEDHOURS) AS SCHEDULE_ESTIMATEDHOURS,
    SUM(ps.SUM_SCHEDULEDHOURS) AS SCHEDULE_SCHEDULEDHOURS,
    SUM(ps.SUM_SCHEDULEDDAYS) AS SCHEDULE_SCHEDULEDDAYS,
    SUM(ps.SUM_BUFFERHOURS) AS SCHEDULE_BUFFERHOURS,
    SUM(ps.SUM_COMPLETED) AS SCHEDULE_COMPLETED,
    SUM(ps.SUM_STARTDATEGAP) AS SCHEDULE_STARTDATEGAP,
    SUM(ps.ROW_COUNT) AS SCHEDULE_ROW_COUNT

FROM DATA_VALIDATION.MART_REVENUE.V_PRODUCTION_JOB_GROUPED pj

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_PROCESSSCHEDULE_GROUPED ps
    ON pj.JOBNUMBER = ps.JOBNUMBER
   AND pj.COMPONENTNUMBER = ps.COMPONENTNUMBER
   AND pj.PROCESSCODE = ps.PROCESSCODE

GROUP BY
    pj.JOBNUMBER,
    pj.COMPONENTNUMBER,
    pj.PROCESSCODE;;
