create or replace view V_PROCESS_MART_CLEAN(
	JOBNUMBER,
	ESTIMATENUMBER,
	COMPONENTNUMBER,
	PROCESSID,
	PROCESSCODE,
	GLACCOUNT,
	GLCOGACCOUNT,
	MATERIALCODE,
	VENDORID,
	VENDORNAME,
	COSTINGMETHOD,
	DUEDATE,
	FIRST_CREATEDATIM,
	LAST_UPDATEDATIM,
	SUM_UNITSPERCYCLE,
	SUM_FIXEDMARKUP,
	SUM_FIXEDCOST,
	SUM_FIXEDQUANTITY,
	SUM_ADDITIONALCHARGE,
	SUM_FIXEDUNITCOST,
	SUM_DISCOUNT,
	SUM_PRODUCTIONQUANTITY,
	SUM_ADDTOTEMPLATEPRICE,
	SUM_UNITCOSTOVERRIDE,
	SUM_USERATEOVERRIDEASPRICE,
	SUM_OVERRIDEUNITSPERCYCLE,
	ORDERPROCESS_ROW_COUNT,
	ORDERVALUE_PRODUCTIONQUANTITY,
	ORDERVALUE_MATERIALQUANTITY,
	ORDERVALUE_PRODUCTIONMINUTES,
	ORDERVALUE_PRODUCTIONCOST,
	ORDERVALUE_MATERIALCOST,
	ORDERVALUE_OSCOST,
	ORDERVALUE_PRODUCTIONPRICE,
	ORDERVALUE_MATERIALPRICE,
	ORDERVALUE_OSPRICE,
	ORDERVALUE_UNITCOST,
	ORDERVALUE_ROYALTYAMOUNT,
	ORDERVALUE_ROW_COUNT,
	SCHEDULE_ESTIMATEDHOURS,
	SCHEDULE_SCHEDULEDHOURS,
	SCHEDULE_SCHEDULEDDAYS,
	SCHEDULE_BUFFERHOURS,
	SCHEDULE_COMPLETED,
	SCHEDULE_STARTDATEGAP,
	SCHEDULE_ROW_COUNT,
	PRODUCTION_PERCENTAGE,
	PRODUCTION_JOB_QUANTITY,
	PRODUCTION_QUANTITY,
	PRODUCTION_ELAPSEDTIME,
	PRODUCTION_UNITCOST,
	PRODUCTION_AICOST,
	PRODUCTION_DMCOST,
	PRODUCTION_WAGECOST,
	PRODUCTION_WIPCOST,
	PRODUCTION_INLINEOPCOST,
	PRODUCTION_ROW_COUNT
) as
WITH order_process AS (
    SELECT
        JOBNUMBER,
        ESTIMATENUMBER,
        COMPONENTNUMBER,
        PROCESSID,
        PROCESSCODE,

        MIN(GLACCOUNT) AS GLACCOUNT,
        MIN(GLCOGACCOUNT) AS GLCOGACCOUNT,
        MIN(MATERIALCODE) AS MATERIALCODE,
        MIN(VENDORID) AS VENDORID,
        MIN(VENDORNAME) AS VENDORNAME,
        MIN(COSTINGMETHOD) AS COSTINGMETHOD,
        MIN(DUEDATE) AS DUEDATE,
        MIN(CREATEDATIM) AS FIRST_CREATEDATIM,
        MAX(UPDATEDATIM) AS LAST_UPDATEDATIM,

        SUM(SUM_UNITSPERCYCLE) AS SUM_UNITSPERCYCLE,
        SUM(SUM_FIXEDMARKUP) AS SUM_FIXEDMARKUP,
        SUM(SUM_FIXEDCOST) AS SUM_FIXEDCOST,
        SUM(SUM_FIXEDQUANTITY) AS SUM_FIXEDQUANTITY,
        SUM(SUM_ADDITIONALCHARGE) AS SUM_ADDITIONALCHARGE,
        SUM(SUM_FIXEDUNITCOST) AS SUM_FIXEDUNITCOST,
        SUM(SUM_DISCOUNT) AS SUM_DISCOUNT,
        SUM(SUM_PRODUCTIONQUANTITY) AS SUM_PRODUCTIONQUANTITY,
        SUM(SUM_ADDTOTEMPLATEPRICE) AS SUM_ADDTOTEMPLATEPRICE,
        SUM(SUM_UNITCOSTOVERRIDE) AS SUM_UNITCOSTOVERRIDE,
        SUM(SUM_USERATEOVERRIDEASPRICE) AS SUM_USERATEOVERRIDEASPRICE,
        SUM(SUM_OVERRIDEUNITSPERCYCLE) AS SUM_OVERRIDEUNITSPERCYCLE,
        SUM(ROW_COUNT) AS ORDERPROCESS_ROW_COUNT

    FROM DATA_VALIDATION.MART_REVENUE.V_ORDERPROCESS_GROUPED
    GROUP BY
        JOBNUMBER,
        ESTIMATENUMBER,
        COMPONENTNUMBER,
        PROCESSID,
        PROCESSCODE
),

process_schedule AS (
    SELECT
        JOBNUMBER,
        COMPONENTNUMBER,
        PROCESSCODE,
        SUM(SUM_ESTIMATEDHOURS) AS SCHEDULE_ESTIMATEDHOURS,
        SUM(SUM_SCHEDULEDHOURS) AS SCHEDULE_SCHEDULEDHOURS,
        SUM(SUM_SCHEDULEDDAYS) AS SCHEDULE_SCHEDULEDDAYS,
        SUM(SUM_BUFFERHOURS) AS SCHEDULE_BUFFERHOURS,
        SUM(SUM_COMPLETED) AS SCHEDULE_COMPLETED,
        SUM(SUM_STARTDATEGAP) AS SCHEDULE_STARTDATEGAP,
        SUM(ROW_COUNT) AS SCHEDULE_ROW_COUNT
    FROM DATA_VALIDATION.MART_REVENUE.V_PROCESSSCHEDULE_GROUPED
    GROUP BY JOBNUMBER, COMPONENTNUMBER, PROCESSCODE
),

production_job AS (
    SELECT
        JOBNUMBER,
        COMPONENTNUMBER,
        PROCESSCODE,
        SUM(SUM_PERCENTAGE) AS PRODUCTION_PERCENTAGE,
        SUM(SUM_JOB_QUANTITY) AS PRODUCTION_JOB_QUANTITY,
        SUM(SUM_QUANTITY) AS PRODUCTION_QUANTITY,
        SUM(SUM_ELAPSEDTIME) AS PRODUCTION_ELAPSEDTIME,
        SUM(SUM_UNITCOST) AS PRODUCTION_UNITCOST,
        SUM(SUM_AICOST) AS PRODUCTION_AICOST,
        SUM(SUM_DMCOST) AS PRODUCTION_DMCOST,
        SUM(SUM_WAGECOST) AS PRODUCTION_WAGECOST,
        SUM(SUM_WIPCOST) AS PRODUCTION_WIPCOST,
        SUM(SUM_INLINEOPCOST) AS PRODUCTION_INLINEOPCOST,
        SUM(ROW_COUNT) AS PRODUCTION_ROW_COUNT
    FROM DATA_VALIDATION.MART_REVENUE.V_PRODUCTION_JOB_GROUPED
    GROUP BY JOBNUMBER, COMPONENTNUMBER, PROCESSCODE
),

order_value AS (
    SELECT
        JOBNUMBER,
        ESTIMATENUMBER,
        COMPONENTNUMBER,
        PROCESSID,
        SUM(TOTAL_PRODUCTIONQUANTITY) AS ORDERVALUE_PRODUCTIONQUANTITY,
        SUM(TOTAL_MATERIALQUANTITY) AS ORDERVALUE_MATERIALQUANTITY,
        SUM(TOTAL_PRODUCTIONMINUTES) AS ORDERVALUE_PRODUCTIONMINUTES,
        SUM(TOTAL_PRODUCTIONCOST) AS ORDERVALUE_PRODUCTIONCOST,
        SUM(TOTAL_MATERIALCOST) AS ORDERVALUE_MATERIALCOST,
        SUM(TOTAL_OSCOST) AS ORDERVALUE_OSCOST,
        SUM(TOTAL_PRODUCTIONPRICE) AS ORDERVALUE_PRODUCTIONPRICE,
        SUM(TOTAL_MATERIALPRICE) AS ORDERVALUE_MATERIALPRICE,
        SUM(TOTAL_OSPRICE) AS ORDERVALUE_OSPRICE,
        SUM(TOTAL_UNITCOST) AS ORDERVALUE_UNITCOST,
        SUM(TOTAL_ROYALTYAMOUNT) AS ORDERVALUE_ROYALTYAMOUNT,
        SUM(ROW_COUNT) AS ORDERVALUE_ROW_COUNT
    FROM DATA_VALIDATION.MART_REVENUE.V_ORDERVALUE_ANALYTICS
    GROUP BY JOBNUMBER, ESTIMATENUMBER, COMPONENTNUMBER, PROCESSID
)

SELECT
    op.*,
    ov.* EXCLUDE (JOBNUMBER, ESTIMATENUMBER, COMPONENTNUMBER, PROCESSID),
    ps.* EXCLUDE (JOBNUMBER, COMPONENTNUMBER, PROCESSCODE),
    pj.* EXCLUDE (JOBNUMBER, COMPONENTNUMBER, PROCESSCODE)

FROM order_process op
LEFT JOIN order_value ov
    ON op.JOBNUMBER = ov.JOBNUMBER
   AND op.ESTIMATENUMBER = ov.ESTIMATENUMBER
   AND op.COMPONENTNUMBER = ov.COMPONENTNUMBER
   AND op.PROCESSID = ov.PROCESSID
LEFT JOIN process_schedule ps
    ON op.JOBNUMBER = ps.JOBNUMBER
   AND op.COMPONENTNUMBER = ps.COMPONENTNUMBER
   AND op.PROCESSCODE = ps.PROCESSCODE
LEFT JOIN production_job pj
    ON op.JOBNUMBER = pj.JOBNUMBER
   AND op.COMPONENTNUMBER = pj.COMPONENTNUMBER
   AND op.PROCESSCODE = pj.PROCESSCODE;;
