create or replace view V_PURCHASING_MART_CLEAN(
	PONUMBER,
	ITEMNUMBER,
	VENDORID,
	POAGENT,
	POSTATUS,
	PLANTID,
	CUSTACCOUNT,
	COMPANYID,
	PO_CURRENCYCODE,
	SECONDARYVENDORID,
	ISSUE_DATE,
	PO_INVOICE_DATE,
	PO_ENTRY_DATE,
	POSTING_DATE,
	PO_FIRST_CREATEDATIM,
	PO_LAST_UPDATEDATIM,
	MATERIALCODE,
	PRODUCTID,
	JOBNUMBER,
	COMPONENTNUMBER,
	GLACCOUNT,
	GLSUBACCOUNT,
	COSTCODE,
	LOCATIONCODE,
	GLCOGACCOUNT,
	GLWIPCODE,
	LINE_CURRENCYCODE,
	LINE_DUE_DATE,
	LINE_ENTRY_DATE,
	LINE_INVOICE_DATE,
	LINE_TOTAL_QUANTITY,
	LINE_TOTAL_UNITCOST,
	LINE_TOTAL_EXTENDEDCOST,
	LINE_TOTAL_FIXEDQUANTITY,
	LINE_TOTAL_FIXEDUNITCOST,
	LINE_TOTAL_TAXAMOUNT,
	LINE_TOTAL_ROLLWEIGHT,
	LINE_TOTAL_UNITCOSTFOREIGN,
	LINE_TOTAL_EXTENDEDCOSTFOREIGN,
	LINE_TOTAL_FIXEDUNITCOSTFOREIGN,
	LINE_ROW_COUNT,
	FIRST_RECEIVEDATE,
	LAST_RECEIVEDATE,
	RECEIPT_TOTAL_QUANTITY,
	RECEIPT_TOTAL_UNITCOST,
	RECEIPT_TOTAL_MISCCOST,
	RECEIPT_TOTAL_EXTENDEDCOST,
	RECEIPT_TOTAL_TAXAMOUNT,
	RECEIPT_TOTAL_FREIGHTCOST,
	RECEIPT_TOTAL_ROLLWEIGHT,
	RECEIPT_TOTAL_RETURNEDQUANTITY,
	RECEIPT_ROW_COUNT,
	DISTINCT_RECEIPT_COUNT,
	DROPSHIP_RECORD_COUNT,
	DISTINCT_DROPSHIP_COUNT,
	SHIPACCOUNT,
	SHIPNAME,
	SHIPCITY,
	SHIPSTATE,
	SHIPZIP,
	SHIPCOUNTRY,
	IMAGE_ROW_COUNT,
	IMAGE_TOTAL_FILESIZE
) as
WITH receipt AS (
    SELECT
        PONUMBER,
        ITEMNUMBER,
        SUM(TOTAL_QUANTITY) AS RECEIPT_TOTAL_QUANTITY,
        SUM(TOTAL_UNITCOST) AS RECEIPT_TOTAL_UNITCOST,
        SUM(TOTAL_MISCCOST) AS RECEIPT_TOTAL_MISCCOST,
        SUM(TOTAL_EXTENDEDCOST) AS RECEIPT_TOTAL_EXTENDEDCOST,
        SUM(TOTAL_TAXAMOUNT) AS RECEIPT_TOTAL_TAXAMOUNT,
        SUM(TOTAL_FREIGHTCOST) AS RECEIPT_TOTAL_FREIGHTCOST,
        SUM(TOTAL_ROLLWEIGHT) AS RECEIPT_TOTAL_ROLLWEIGHT,
        SUM(TOTAL_RETURNEDQUANTITY) AS RECEIPT_TOTAL_RETURNEDQUANTITY,
        SUM(RECEIPT_ROW_COUNT) AS RECEIPT_ROW_COUNT,
        SUM(DISTINCT_RECEIPT_COUNT) AS DISTINCT_RECEIPT_COUNT,
        MIN(FIRST_RECEIVEDATE) AS FIRST_RECEIVEDATE,
        MAX(LAST_RECEIVEDATE) AS LAST_RECEIVEDATE
    FROM DATA_VALIDATION.MART_REVENUE.V_PORECEIPT_ANALYTICS
    GROUP BY PONUMBER, ITEMNUMBER
),

dropship AS (
    SELECT
        PONUMBER,
        COUNT(*) AS DROPSHIP_RECORD_COUNT,
        COUNT(DISTINCT DROPSHIPNO) AS DISTINCT_DROPSHIP_COUNT,
        MIN(SHIPACCOUNT) AS SHIPACCOUNT,
        MIN(SHIPNAME) AS SHIPNAME,
        MIN(SHIPCITY) AS SHIPCITY,
        MIN(SHIPSTATE) AS SHIPSTATE,
        MIN(SHIPZIP) AS SHIPZIP,
        MIN(SHIPCOUNTRY) AS SHIPCOUNTRY
    FROM DATA_VALIDATION.MART_REVENUE.V_PODROPSHIP_ANALYTICS
    GROUP BY PONUMBER
),

image AS (
    SELECT
        PONUMBER,
        SUM(IMAGE_ROW_COUNT) AS IMAGE_ROW_COUNT,
        SUM(TOTAL_FILESIZE) AS IMAGE_TOTAL_FILESIZE
    FROM DATA_VALIDATION.MART_REVENUE.V_POIMAGE_ANALYTICS
    GROUP BY PONUMBER
)

SELECT
    li.PONUMBER,
    li.ITEMNUMBER,

    ph.VENDORID,
    ph.POAGENT,
    ph.POSTATUS,
    ph.PLANTID,
    ph.CUSTACCOUNT,
    ph.COMPANYID,
    ph.CURRENCYCODE AS PO_CURRENCYCODE,
    ph.SECONDARYVENDORID,
    ph.ISSUE_DATE,
    ph.INVOICE_DATE AS PO_INVOICE_DATE,
    ph.ENTRY_DATE AS PO_ENTRY_DATE,
    ph.POSTING_DATE,
    ph.FIRST_CREATEDATIM AS PO_FIRST_CREATEDATIM,
    ph.LAST_UPDATEDATIM AS PO_LAST_UPDATEDATIM,

    li.MATERIALCODE,
    li.PRODUCTID,
    li.JOBNUMBER,
    li.COMPONENTNUMBER,
    li.GLACCOUNT,
    li.GLSUBACCOUNT,
    li.COSTCODE,
    li.LOCATIONCODE,
    li.GLCOGACCOUNT,
    li.GLWIPCODE,
    li.CURRENCYCODE AS LINE_CURRENCYCODE,
    li.DUE_DATE AS LINE_DUE_DATE,
    li.ENTRY_DATE AS LINE_ENTRY_DATE,
    li.INVOICE_DATE AS LINE_INVOICE_DATE,

    li.TOTAL_QUANTITY AS LINE_TOTAL_QUANTITY,
    li.TOTAL_UNITCOST AS LINE_TOTAL_UNITCOST,
    li.TOTAL_EXTENDEDCOST AS LINE_TOTAL_EXTENDEDCOST,
    li.TOTAL_FIXEDQUANTITY AS LINE_TOTAL_FIXEDQUANTITY,
    li.TOTAL_FIXEDUNITCOST AS LINE_TOTAL_FIXEDUNITCOST,
    li.TOTAL_TAXAMOUNT AS LINE_TOTAL_TAXAMOUNT,
    li.TOTAL_ROLLWEIGHT AS LINE_TOTAL_ROLLWEIGHT,
    li.TOTAL_UNITCOSTFOREIGN AS LINE_TOTAL_UNITCOSTFOREIGN,
    li.TOTAL_EXTENDEDCOSTFOREIGN AS LINE_TOTAL_EXTENDEDCOSTFOREIGN,
    li.TOTAL_FIXEDUNITCOSTFOREIGN AS LINE_TOTAL_FIXEDUNITCOSTFOREIGN,
    li.ROW_COUNT AS LINE_ROW_COUNT,

    r.FIRST_RECEIVEDATE,
    r.LAST_RECEIVEDATE,
    r.RECEIPT_TOTAL_QUANTITY,
    r.RECEIPT_TOTAL_UNITCOST,
    r.RECEIPT_TOTAL_MISCCOST,
    r.RECEIPT_TOTAL_EXTENDEDCOST,
    r.RECEIPT_TOTAL_TAXAMOUNT,
    r.RECEIPT_TOTAL_FREIGHTCOST,
    r.RECEIPT_TOTAL_ROLLWEIGHT,
    r.RECEIPT_TOTAL_RETURNEDQUANTITY,
    r.RECEIPT_ROW_COUNT,
    r.DISTINCT_RECEIPT_COUNT,

    ds.DROPSHIP_RECORD_COUNT,
    ds.DISTINCT_DROPSHIP_COUNT,
    ds.SHIPACCOUNT,
    ds.SHIPNAME,
    ds.SHIPCITY,
    ds.SHIPSTATE,
    ds.SHIPZIP,
    ds.SHIPCOUNTRY,

    img.IMAGE_ROW_COUNT,
    img.IMAGE_TOTAL_FILESIZE

FROM DATA_VALIDATION.MART_REVENUE.V_POLINEITEM_ANALYTICS li

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_POHEADER_ANALYTICS ph
    ON li.PONUMBER = ph.PONUMBER

LEFT JOIN receipt r
    ON li.PONUMBER = r.PONUMBER
   AND li.ITEMNUMBER = r.ITEMNUMBER

LEFT JOIN dropship ds
    ON li.PONUMBER = ds.PONUMBER

LEFT JOIN image img
    ON TO_VARCHAR(li.PONUMBER) = TO_VARCHAR(img.PONUMBER);;
