create or replace view V_REVENUE_REPORT_BASE_SAMPLE(
	PROGRAM_TRANSACTION,
	MFG_SITE,
	REV_TYPE,
	SALES_PERSON,
	CUSTACCOUNT,
	CUSTNAME,
	JOBNUMBER,
	DOCUMENTNUMBER,
	TRANSACTIONNUMBER,
	REVENUE_MONTH,
	NET_REVENUE,
	TAX_AMOUNT,
	TOTAL_VALUE,
	COST_VALUE,
	GROSS_MARGIN,
	QTY_SHIPPED
) as
SELECT
    COALESCE(JOBDESCRIPTION, LINE_DESCRIPTION) AS PROGRAM_TRANSACTION,
    PLANTID AS MFG_SITE,
    TRANSACTIONTYPE AS REV_TYPE,
    SALESREPCODE AS SALES_PERSON,
    CUSTACCOUNT,
    CUSTNAME,
    JOBNUMBER,
    DOCUMENTNUMBER,
    TRANSACTIONNUMBER,
    REVENUE_MONTH,

    SUM(NET_REVENUE) AS NET_REVENUE,
    SUM(TAX_AMOUNT) AS TAX_AMOUNT,
    SUM(TOTAL_VALUE) AS TOTAL_VALUE,
    SUM(COST_VALUE) AS COST_VALUE,
    SUM(GROSS_MARGIN) AS GROSS_MARGIN,
    SUM(QTY_SHIPPED) AS QTY_SHIPPED

FROM DATA_VALIDATION.MART_REVENUE.V_MONTHLY_REVENUE_SAMPLE
GROUP BY
    PROGRAM_TRANSACTION,
    MFG_SITE,
    REV_TYPE,
    SALES_PERSON,
    CUSTACCOUNT,
    CUSTNAME,
    JOBNUMBER,
    DOCUMENTNUMBER,
    TRANSACTIONNUMBER,
    REVENUE_MONTH;;
