create or replace view V_REQUISITION_RFQ_ENRICHED(
	CODE,
	JOBNUMBER,
	COMPONENTNUMBER,
	MATERIALCODE,
	GLACCOUNT,
	VENDORPRODUCTID,
	COSTINGMETHOD,
	LINEITEMTYPE,
	ENTRYDATE,
	VENDORID,
	LOCATIONCODE,
	MULTILOCATION,
	PLANTID,
	DUEDATE,
	CREATEDATIM,
	UPDATEDATIM,
	MANUFACTURERITEMNUMBER,
	SUM_QUANTITY,
	SUM_UNITCOST,
	SUM_EXTENDEDCOST,
	SUM_FIXEDQUANTITY,
	SUM_FIXEDUNITCOST,
	SUM_QUANTITYTOORDER,
	ROW_COUNT,
	RFQNUMBER,
	RFQ_ESTIMATENUMBER,
	RFQ_ORDERNUMBER,
	RFQ_PRICINGDONE,
	RFQ_CUSTACCOUNT,
	RFQ_CUSTNAME,
	RFQ_CUSTSTATE,
	RFQ_CUSTZIP,
	RFQDUEDATE,
	RFQ_ARJOBCLOSEOUT,
	RFQ_COMPONENTTYPE,
	RFQ_COMPONENT_TOTAL_QUANTITY,
	RFQ_COMPONENT_TOTAL_PRICE,
	RFQCOMPONENTVALUEID,
	RFQ_COMPONENT_VALUE,
	RFQHEADER_ROW_COUNT,
	RFQCOMPONENT_ROW_COUNT,
	RFQCOMPONENTVALUE_ROW_COUNT
) as
SELECT
    r.*,

    rh.RFQNUMBER,
    rh.ESTIMATENUMBER AS RFQ_ESTIMATENUMBER,
    rh.ORDERNUMBER AS RFQ_ORDERNUMBER,
    rh.PRICINGDONE AS RFQ_PRICINGDONE,
    rh.CUSTACCOUNT AS RFQ_CUSTACCOUNT,
    rh.CUSTNAME AS RFQ_CUSTNAME,
    rh.CUSTSTATE AS RFQ_CUSTSTATE,
    rh.CUSTZIP AS RFQ_CUSTZIP,
    rh.RFQDUEDATE,
    rh.ARJOBCLOSEOUT AS RFQ_ARJOBCLOSEOUT,

    rc.COMPONENTTYPE AS RFQ_COMPONENTTYPE,
    rc.SUM_TOTAL_QUANTITY AS RFQ_COMPONENT_TOTAL_QUANTITY,
    rc.SUM_TOTAL_PRICE AS RFQ_COMPONENT_TOTAL_PRICE,

    rcv.RFQCOMPONENTVALUEID,
    rcv.SUM_VALUE AS RFQ_COMPONENT_VALUE,

    rh.ROW_COUNT AS RFQHEADER_ROW_COUNT,
    rc.ROW_COUNT AS RFQCOMPONENT_ROW_COUNT,
    rcv.ROW_COUNT AS RFQCOMPONENTVALUE_ROW_COUNT

FROM DATA_VALIDATION.MART_REVENUE.V_REQUISITION_GROUPED r

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_RFQHEADER_GROUPED rh
    ON TO_VARCHAR(r.JOBNUMBER) = TO_VARCHAR(rh.ORDERNUMBER)

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_RFQCOMPONENT_GROUPED rc
    ON rh.RFQNUMBER = rc.RFQNUMBER
   AND r.COMPONENTNUMBER = rc.COMPONENTNUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.V_RFQCOMPONENTVALUE_GROUPED rcv
    ON rc.RFQNUMBER = rcv.RFQNUMBER
   AND rc.COMPONENTNUMBER = rcv.COMPONENTNUMBER;;
