create or replace view V_REVENUE_BY_CUSTOMER_MONTH(
	REVENUE_MONTH,
	CUSTACCOUNT,
	CUSTNAME,
	INVOICE_COUNT,
	JOB_COUNT,
	QTY_ORDERED,
	QTY_SHIPPED,
	EXTENDED_VALUE,
	DISCOUNT_VALUE,
	NET_REVENUE,
	TAX_AMOUNT,
	TOTAL_VALUE,
	COST_VALUE,
	GROSS_MARGIN
) as
SELECT
    REVENUE_MONTH,
    CUSTACCOUNT,
    CUSTNAME,

    COUNT(DISTINCT TRANSACTIONNUMBER) AS INVOICE_COUNT,
    COUNT(DISTINCT JOBNUMBER) AS JOB_COUNT,

    SUM(QTY_ORDERED) AS QTY_ORDERED,
    SUM(QTY_SHIPPED) AS QTY_SHIPPED,
    SUM(EXTENDED_VALUE) AS EXTENDED_VALUE,
    SUM(DISCOUNT_VALUE) AS DISCOUNT_VALUE,
    SUM(NET_REVENUE) AS NET_REVENUE,
    SUM(TAX_AMOUNT) AS TAX_AMOUNT,
    SUM(TOTAL_VALUE) AS TOTAL_VALUE,
    SUM(COST_VALUE) AS COST_VALUE,
    SUM(GROSS_MARGIN) AS GROSS_MARGIN

FROM DATA_VALIDATION.MART_REVENUE.V_MONTHLY_REVENUE
GROUP BY
    REVENUE_MONTH,
    CUSTACCOUNT,
    CUSTNAME;;
