create or replace view V_REVENUE_BY_CUSTOMER_MONTH_SAMPLE(
	REVENUE_MONTH,
	CUSTACCOUNT,
	CUSTNAME,
	INVOICE_COUNT,
	JOB_COUNT,
	NET_REVENUE,
	TOTAL_VALUE
) as
SELECT
    REVENUE_MONTH,
    CUSTACCOUNT,
    CUSTNAME,

    COUNT(DISTINCT TRANSACTIONNUMBER) AS INVOICE_COUNT,
    COUNT(DISTINCT JOBNUMBER) AS JOB_COUNT,

    SUM(NET_REVENUE) AS NET_REVENUE,
    SUM(TOTAL_VALUE) AS TOTAL_VALUE

FROM MART_REVENUE.V_MONTHLY_REVENUE_SAMPLE
GROUP BY
    REVENUE_MONTH,
    CUSTACCOUNT,
    CUSTNAME;;
