create or replace view V_RFQTEMPLATEITEM_GROUPED(
	RFQTEMPLATEITEMID,
	RFQTEMPLATEID,
	TYPE,
	ENTRYDATE,
	CREATEDATIM,
	UPDATEDATIM,
	SUM_MINVALUE,
	SUM_MAXVALUE,
	SUM_DEFAULTVALUE,
	ROW_COUNT
) as
SELECT
    RFQTEMPLATEITEMID,
    RFQTEMPLATEID,
    TYPE,
    ENTRYDATE,
    CREATEDATIM,
    UPDATEDATIM,

    SUM(MINVALUE) AS SUM_MINVALUE,
    SUM(MAXVALUE) AS SUM_MAXVALUE,
    SUM(DEFAULTVALUE) AS SUM_DEFAULTVALUE,

    COUNT(*) AS ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.RFQTEMPLATEITEM
GROUP BY
    RFQTEMPLATEITEMID,
    RFQTEMPLATEID,
    TYPE,
    ENTRYDATE,
    CREATEDATIM,
    UPDATEDATIM;;
