create or replace view V_RFQCOMPONENT_GROUPED(
	RFQNUMBER,
	COMPONENTNUMBER,
	COMPONENTTYPE,
	ENTRYDATE,
	CREATEDATIM,
	UPDATEDATIM,
	SUM_QUANTITY1,
	SUM_QUANTITY2,
	SUM_QUANTITY3,
	SUM_QUANTITY4,
	SUM_QUANTITY5,
	SUM_QUANTITY6,
	SUM_TOTAL_QUANTITY,
	SUM_PRICE1,
	SUM_PRICE2,
	SUM_PRICE3,
	SUM_PRICE4,
	SUM_PRICE5,
	SUM_PRICE6,
	SUM_TOTAL_PRICE,
	ROW_COUNT
) as
SELECT
    RFQNUMBER,
    COMPONENTNUMBER,
    COMPONENTTYPE,
    ENTRYDATE,
    CREATEDATIM,
    UPDATEDATIM,

    SUM(QUANTITY1) AS SUM_QUANTITY1,
    SUM(QUANTITY2) AS SUM_QUANTITY2,
    SUM(QUANTITY3) AS SUM_QUANTITY3,
    SUM(QUANTITY4) AS SUM_QUANTITY4,
    SUM(QUANTITY5) AS SUM_QUANTITY5,
    SUM(QUANTITY6) AS SUM_QUANTITY6,

    SUM(
        COALESCE(QUANTITY1, 0) +
        COALESCE(QUANTITY2, 0) +
        COALESCE(QUANTITY3, 0) +
        COALESCE(QUANTITY4, 0) +
        COALESCE(QUANTITY5, 0) +
        COALESCE(QUANTITY6, 0)
    ) AS SUM_TOTAL_QUANTITY,

    SUM(PRICE1) AS SUM_PRICE1,
    SUM(PRICE2) AS SUM_PRICE2,
    SUM(PRICE3) AS SUM_PRICE3,
    SUM(PRICE4) AS SUM_PRICE4,
    SUM(PRICE5) AS SUM_PRICE5,
    SUM(PRICE6) AS SUM_PRICE6,

    SUM(
        COALESCE(PRICE1, 0) +
        COALESCE(PRICE2, 0) +
        COALESCE(PRICE3, 0) +
        COALESCE(PRICE4, 0) +
        COALESCE(PRICE5, 0) +
        COALESCE(PRICE6, 0)
    ) AS SUM_TOTAL_PRICE,

    COUNT(*) AS ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.RFQCOMPONENT
GROUP BY
    RFQNUMBER,
    COMPONENTNUMBER,
    COMPONENTTYPE,
    ENTRYDATE,
    CREATEDATIM,
    UPDATEDATIM;;
