create or replace view V_RFQHEADER_GROUPED(
	RFQNUMBER,
	ESTIMATENUMBER,
	ORDERNUMBER,
	PRICINGDONE,
	CUSTACCOUNT,
	CUSTNAME,
	CUSTSTATE,
	CUSTZIP,
	DUEDATE,
	RFQDUEDATE,
	ENTRYDATE,
	CREATEDATIM,
	UPDATEDATIM,
	ARJOBCLOSEOUT,
	ROW_COUNT
) as
SELECT
    RFQNUMBER,
    ESTIMATENUMBER,
    ORDERNUMBER,
    PRICINGDONE,
    CUSTACCOUNT,
    CUSTNAME,
    CUSTSTATE,
    CUSTZIP,
    DUEDATE,
    RFQDUEDATE,
    ENTRYDATE,
    CREATEDATIM,
    UPDATEDATIM,
    ARJOBCLOSEOUT,

    COUNT(*) AS ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.RFQHEADER
GROUP BY
    RFQNUMBER,
    ESTIMATENUMBER,
    ORDERNUMBER,
    PRICINGDONE,
    CUSTACCOUNT,
    CUSTNAME,
    CUSTSTATE,
    CUSTZIP,
    DUEDATE,
    RFQDUEDATE,
    ENTRYDATE,
    CREATEDATIM,
    UPDATEDATIM,
    ARJOBCLOSEOUT;;
