create or replace view V_RFQCOMPONENTVALUE_GROUPED(
	RFQCOMPONENTVALUEID,
	RFQNUMBER,
	COMPONENTNUMBER,
	ENTRYDATE,
	CREATEDATIM,
	UPDATEDATIM,
	SUM_VALUE,
	ROW_COUNT
) as
SELECT
    RFQCOMPONENTVALUEID,
    RFQNUMBER,
    COMPONENTNUMBER,
    ENTRYDATE,
    CREATEDATIM,
    UPDATEDATIM,

    SUM(VALUE) AS SUM_VALUE,

    COUNT(*) AS ROW_COUNT

FROM DATA_VALIDATION.RAW_SQL_SERVER.RFQCOMPONENTVALUE
GROUP BY
    RFQCOMPONENTVALUEID,
    RFQNUMBER,
    COMPONENTNUMBER,
    ENTRYDATE,
    CREATEDATIM,
    UPDATEDATIM;;
