create or replace view V_VENDOR_MART_CLEAN(
	VENDORID,
	PRODUCTID,
	SUM_BALANCEBFWD,
	SUM_BALANCE4,
	SUM_BALANCE3,
	SUM_BALANCE2,
	SUM_BALANCE1,
	SUM_BALANCE0,
	SUM_BALANCEDUE,
	SUM_BALANCEFUTURE,
	SUM_BALANCEHELD,
	SUM_LASTINVOICEVAL,
	SUM_LASTPAYMENTVAL,
	LASTINVOICEDATE,
	LASTPAYMENTDATE,
	SUM_INVOICESPAID,
	VENDOR_BALANCE_ROW_COUNT,
	PRICINGMETHOD,
	DEFAULTGLSALESCODE,
	GLCOGCODE,
	GLWIPCODE,
	GLEXPENSECODE,
	SUM_FIXEDCOST,
	SUM_MARKUP,
	SUM_MINIMUMCOST,
	VENDOR_PRODUCT_ROW_COUNT,
	FIRST_PRODUCT_ENTRYDATE,
	FIRST_PRODUCT_CREATEDATIM,
	LAST_PRODUCT_UPDATEDATIM,
	SUM_PRICE_QUANTITY,
	SUM_PRICE_COST,
	VENDOR_PRODUCT_PRICE_ROW_COUNT,
	FIRST_PRODUCT_PRICE_ENTRYDATE,
	FIRST_PRODUCT_PRICE_CREATEDATIM
) as
WITH vendor_balance AS (
    SELECT
        VENDORID,

        SUM(SUM_BALANCEBFWD) AS SUM_BALANCEBFWD,
        SUM(SUM_BALANCE4) AS SUM_BALANCE4,
        SUM(SUM_BALANCE3) AS SUM_BALANCE3,
        SUM(SUM_BALANCE2) AS SUM_BALANCE2,
        SUM(SUM_BALANCE1) AS SUM_BALANCE1,
        SUM(SUM_BALANCE0) AS SUM_BALANCE0,
        SUM(SUM_BALANCEDUE) AS SUM_BALANCEDUE,
        SUM(SUM_BALANCEFUTURE) AS SUM_BALANCEFUTURE,
        SUM(SUM_BALANCEHELD) AS SUM_BALANCEHELD,
        SUM(SUM_LASTINVOICEVAL) AS SUM_LASTINVOICEVAL,
        SUM(SUM_LASTPAYMENTVAL) AS SUM_LASTPAYMENTVAL,

        MAX(LASTINVOICEDATE) AS LASTINVOICEDATE,
        MAX(LASTPAYMENTDATE) AS LASTPAYMENTDATE,
        SUM(INVOICESPAID) AS SUM_INVOICESPAID,
        SUM(VENDOR_BALANCE_ROW_COUNT) AS VENDOR_BALANCE_ROW_COUNT

    FROM DATA_VALIDATION.MART_REVENUE.V_VENDOR_BALANCES_PRODUCTS_PRICES
    GROUP BY
        VENDORID
),

vendor_product AS (
    SELECT
        VENDORID,
        PRODUCTID,

        MIN(PRICINGMETHOD) AS PRICINGMETHOD,
        MIN(DEFAULTGLSALESCODE) AS DEFAULTGLSALESCODE,
        MIN(GLCOGCODE) AS GLCOGCODE,
        MIN(GLWIPCODE) AS GLWIPCODE,
        MIN(GLEXPENSECODE) AS GLEXPENSECODE,

        SUM(SUM_FIXEDCOST) AS SUM_FIXEDCOST,
        SUM(SUM_MARKUP) AS SUM_MARKUP,
        SUM(SUM_MINIMUMCOST) AS SUM_MINIMUMCOST,
        SUM(VENDOR_PRODUCT_ROW_COUNT) AS VENDOR_PRODUCT_ROW_COUNT,

        MIN(PRODUCT_ENTRYDATE) AS FIRST_PRODUCT_ENTRYDATE,
        MIN(PRODUCT_CREATEDATIM) AS FIRST_PRODUCT_CREATEDATIM,
        MAX(PRODUCT_UPDATEDATIM) AS LAST_PRODUCT_UPDATEDATIM

    FROM DATA_VALIDATION.MART_REVENUE.V_VENDOR_BALANCES_PRODUCTS_PRICES
    WHERE PRODUCTID IS NOT NULL
    GROUP BY
        VENDORID,
        PRODUCTID
),

vendor_price AS (
    SELECT
        VENDORID,
        PRODUCTID,

        SUM(SUM_PRICE_QUANTITY) AS SUM_PRICE_QUANTITY,
        SUM(SUM_PRICE_COST) AS SUM_PRICE_COST,
        SUM(VENDOR_PRODUCT_PRICE_ROW_COUNT) AS VENDOR_PRODUCT_PRICE_ROW_COUNT,

        MIN(PRODUCT_PRICE_ENTRYDATE) AS FIRST_PRODUCT_PRICE_ENTRYDATE,
        MIN(PRODUCT_PRICE_CREATEDATIM) AS FIRST_PRODUCT_PRICE_CREATEDATIM

    FROM DATA_VALIDATION.MART_REVENUE.V_VENDOR_BALANCES_PRODUCTS_PRICES
    WHERE PRODUCTID IS NOT NULL
    GROUP BY
        VENDORID,
        PRODUCTID
)

SELECT
    vp.VENDORID,
    vp.PRODUCTID,

    vb.SUM_BALANCEBFWD,
    vb.SUM_BALANCE4,
    vb.SUM_BALANCE3,
    vb.SUM_BALANCE2,
    vb.SUM_BALANCE1,
    vb.SUM_BALANCE0,
    vb.SUM_BALANCEDUE,
    vb.SUM_BALANCEFUTURE,
    vb.SUM_BALANCEHELD,
    vb.SUM_LASTINVOICEVAL,
    vb.SUM_LASTPAYMENTVAL,
    vb.LASTINVOICEDATE,
    vb.LASTPAYMENTDATE,
    vb.SUM_INVOICESPAID,
    vb.VENDOR_BALANCE_ROW_COUNT,

    vp.PRICINGMETHOD,
    vp.DEFAULTGLSALESCODE,
    vp.GLCOGCODE,
    vp.GLWIPCODE,
    vp.GLEXPENSECODE,
    vp.SUM_FIXEDCOST,
    vp.SUM_MARKUP,
    vp.SUM_MINIMUMCOST,
    vp.VENDOR_PRODUCT_ROW_COUNT,
    vp.FIRST_PRODUCT_ENTRYDATE,
    vp.FIRST_PRODUCT_CREATEDATIM,
    vp.LAST_PRODUCT_UPDATEDATIM,

    vprice.SUM_PRICE_QUANTITY,
    vprice.SUM_PRICE_COST,
    vprice.VENDOR_PRODUCT_PRICE_ROW_COUNT,
    vprice.FIRST_PRODUCT_PRICE_ENTRYDATE,
    vprice.FIRST_PRODUCT_PRICE_CREATEDATIM

FROM vendor_product vp

LEFT JOIN vendor_balance vb
    ON vp.VENDORID = vb.VENDORID

LEFT JOIN vendor_price vprice
    ON vp.VENDORID = vprice.VENDORID
   AND vp.PRODUCTID = vprice.PRODUCTID;;
