create or replace view V_VENDOR_BALANCES_PRODUCTS_PRICES(
	VENDORID,
	CREATEDATIM,
	UPDATEDATIM,
	LASTINVOICEDATE,
	LASTPAYMENTDATE,
	INVOICESPAID,
	SUM_BALANCEBFWD,
	SUM_BALANCE4,
	SUM_BALANCE3,
	SUM_BALANCE2,
	SUM_BALANCE1,
	SUM_BALANCE0,
	SUM_BALANCEDUE,
	SUM_BALANCEFUTURE,
	SUM_BALANCEHELD,
	SUM_LASTINVOICEVAL,
	SUM_LASTPAYMENTVAL,
	SUM_BALANCEBFWDFOREIGN,
	SUM_BALANCE4FOREIGN,
	SUM_BALANCE3FOREIGN,
	SUM_BALANCE2FOREIGN,
	SUM_BALANCE1FOREIGN,
	SUM_BALANCE0FOREIGN,
	SUM_LASTINVOICEVALFOREIGN,
	SUM_LASTPAYMENTVALFOREIGN,
	VENDOR_BALANCE_ROW_COUNT,
	PRODUCTID,
	PRICINGMETHOD,
	PRODUCT_ENTRYDATE,
	PRODUCT_CREATEDATIM,
	PRODUCT_UPDATEDATIM,
	DEFAULTGLSALESCODE,
	GLCOGCODE,
	GLWIPCODE,
	GLEXPENSECODE,
	SUM_FIXEDCOST,
	SUM_MARKUP,
	SUM_MINIMUMCOST,
	VENDOR_PRODUCT_ROW_COUNT,
	PRODUCT_PRICE_ENTRYDATE,
	PRODUCT_PRICE_CREATEDATIM,
	SUM_PRICE_QUANTITY,
	SUM_PRICE_COST,
	VENDOR_PRODUCT_PRICE_ROW_COUNT
) as
WITH vendor_balances AS (
    SELECT
        VENDORID,
        CREATEDATIM,
        UPDATEDATIM,
        LASTINVOICEDATE,
        LASTPAYMENTDATE,
        INVOICESPAID,

        SUM(BALANCEBFWD) AS SUM_BALANCEBFWD,
        SUM(BALANCE4) AS SUM_BALANCE4,
        SUM(BALANCE3) AS SUM_BALANCE3,
        SUM(BALANCE2) AS SUM_BALANCE2,
        SUM(BALANCE1) AS SUM_BALANCE1,
        SUM(BALANCE0) AS SUM_BALANCE0,
        SUM(BALANCEDUE) AS SUM_BALANCEDUE,
        SUM(BALANCEFUTURE) AS SUM_BALANCEFUTURE,
        SUM(BALANCEHELD) AS SUM_BALANCEHELD,
        SUM(LASTINVOICEVAL) AS SUM_LASTINVOICEVAL,
        SUM(LASTPAYMENTVAL) AS SUM_LASTPAYMENTVAL,

        SUM(BALANCEBFWDFOREIGN) AS SUM_BALANCEBFWDFOREIGN,
        SUM(BALANCE4FOREIGN) AS SUM_BALANCE4FOREIGN,
        SUM(BALANCE3FOREIGN) AS SUM_BALANCE3FOREIGN,
        SUM(BALANCE2FOREIGN) AS SUM_BALANCE2FOREIGN,
        SUM(BALANCE1FOREIGN) AS SUM_BALANCE1FOREIGN,
        SUM(BALANCE0FOREIGN) AS SUM_BALANCE0FOREIGN,
        SUM(LASTINVOICEVALFOREIGN) AS SUM_LASTINVOICEVALFOREIGN,
        SUM(LASTPAYMENTVALFOREIGN) AS SUM_LASTPAYMENTVALFOREIGN,

        COUNT(*) AS VENDOR_BALANCE_ROW_COUNT

    FROM DATA_VALIDATION.RAW_SQL_SERVER.VENDORBALANCES
    GROUP BY
        VENDORID,
        CREATEDATIM,
        UPDATEDATIM,
        LASTINVOICEDATE,
        LASTPAYMENTDATE,
        INVOICESPAID
),

vendor_product AS (
    SELECT
        VENDORID,
        PRODUCTID,
        PRICINGMETHOD,
        ENTRYDATE,
        CREATEDATIM,
        UPDATEDATIM,
        DEFAULTGLSALESCODE,
        GLCOGCODE,
        GLWIPCODE,
        GLEXPENSECODE,

        SUM(FIXEDCOST) AS SUM_FIXEDCOST,
        SUM(MARKUP) AS SUM_MARKUP,
        SUM(MINIMUMCOST) AS SUM_MINIMUMCOST,

        COUNT(*) AS VENDOR_PRODUCT_ROW_COUNT

    FROM DATA_VALIDATION.RAW_SQL_SERVER.VENDORPRODUCT
    GROUP BY
        VENDORID,
        PRODUCTID,
        PRICINGMETHOD,
        ENTRYDATE,
        CREATEDATIM,
        UPDATEDATIM,
        DEFAULTGLSALESCODE,
        GLCOGCODE,
        GLWIPCODE,
        GLEXPENSECODE
),

vendor_product_price AS (
    SELECT
        VENDORID,
        PRODUCTID,
        ENTRYDATE,
        CREATEDATIM,

        SUM(QUANTITY) AS SUM_PRICE_QUANTITY,
        SUM(COST) AS SUM_PRICE_COST,

        COUNT(*) AS VENDOR_PRODUCT_PRICE_ROW_COUNT

    FROM DATA_VALIDATION.RAW_SQL_SERVER.VENDORPRODUCTPRICE
    GROUP BY
        VENDORID,
        PRODUCTID,
        ENTRYDATE,
        CREATEDATIM
)

SELECT
    vb.*,

    vp.PRODUCTID,
    vp.PRICINGMETHOD,
    vp.ENTRYDATE AS PRODUCT_ENTRYDATE,
    vp.CREATEDATIM AS PRODUCT_CREATEDATIM,
    vp.UPDATEDATIM AS PRODUCT_UPDATEDATIM,
    vp.DEFAULTGLSALESCODE,
    vp.GLCOGCODE,
    vp.GLWIPCODE,
    vp.GLEXPENSECODE,
    vp.SUM_FIXEDCOST,
    vp.SUM_MARKUP,
    vp.SUM_MINIMUMCOST,
    vp.VENDOR_PRODUCT_ROW_COUNT,

    vpp.ENTRYDATE AS PRODUCT_PRICE_ENTRYDATE,
    vpp.CREATEDATIM AS PRODUCT_PRICE_CREATEDATIM,
    vpp.SUM_PRICE_QUANTITY,
    vpp.SUM_PRICE_COST,
    vpp.VENDOR_PRODUCT_PRICE_ROW_COUNT

FROM vendor_balances vb
LEFT JOIN vendor_product vp
    ON vb.VENDORID = vp.VENDORID

LEFT JOIN vendor_product_price vpp
    ON vp.VENDORID = vpp.VENDORID
   AND vp.PRODUCTID = vpp.PRODUCTID;;
