/*================================================================================
BUILD_MART_REVENUE.sql
Purpose:
    Build the revenue/order analytics mart from DATA_VALIDATION.RAW_SQL_SERVER.

Inputs:
    DATA_VALIDATION.RAW_SQL_SERVER.ORDERHEADER
    DATA_VALIDATION.RAW_SQL_SERVER.ORDERCOMPONENT
    DATA_VALIDATION.RAW_SQL_SERVER.ORDERVALUE
    DATA_VALIDATION.RAW_SQL_SERVER.ARTRANSACTIONLINE
    DATA_VALIDATION.RAW_SQL_SERVER.SHIPMENT
    DATA_VALIDATION.RAW_SQL_SERVER.ORDERPROCESS

Outputs:
    DATA_VALIDATION.MART_REVENUE.FACT_ORDER_COMPONENT
    DATA_VALIDATION.MART_REVENUE.DIM_CUSTOMER
    DATA_VALIDATION.MART_REVENUE.DIM_SALESREP
    DATA_VALIDATION.MART_REVENUE.DIM_PLANT
    DATA_VALIDATION.MART_REVENUE.V_ORDER_COMPONENT_ANALYTICS
    DATA_VALIDATION.MART_REVENUE.MONTHLY_REVENUE_SUMMARY
    DATA_VALIDATION.MART_REVENUE.V_MONTHLY_REVENUE_TRENDS
    DATA_VALIDATION.MART_REVENUE.V_TOP_CUSTOMERS
    DATA_VALIDATION.MART_REVENUE.V_SALESREP_PERFORMANCE
    DATA_VALIDATION.MART_REVENUE.V_PLANT_PERFORMANCE
    DATA_VALIDATION.DATA_VALIDATION_DEV.MART_QUALITY_CHECKS

Expected grain:
    FACT_ORDER_COMPONENT = 1 row per JOBNUMBER + COMPONENTNUMBER

Notes:
    Several source date fields are stored as nanosecond Unix timestamps.
    Use: TO_DATE(TO_TIMESTAMP_NTZ(<date_column> / 1000000000))
================================================================================*/


/*==============================================================================
00 - SCHEMA SETUP
==============================================================================*/

CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.MART_REVENUE;
CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.DATA_VALIDATION_DEV;


/*==============================================================================
01 - HELPER AGGREGATE TABLES
==============================================================================*/

CREATE OR REPLACE TABLE DATA_VALIDATION.MART_REVENUE.ORDER_VALUE_AGG AS
SELECT
    JOBNUMBER,
    COMPONENTNUMBER,

    SUM(PRODUCTIONCOST) AS PRODUCTIONCOST,
    SUM(MATERIALCOST) AS MATERIALCOST,
    SUM(OSCOST) AS OSCOST,

    SUM(PRODUCTIONPRICE) AS PRODUCTIONPRICE,
    SUM(MATERIALPRICE) AS MATERIALPRICE,
    SUM(OSPRICE) AS OSPRICE,

    SUM(
        COALESCE(PRODUCTIONCOST, 0)
      + COALESCE(MATERIALCOST, 0)
      + COALESCE(OSCOST, 0)
    ) AS TOTAL_COST,

    SUM(
        COALESCE(PRODUCTIONPRICE, 0)
      + COALESCE(MATERIALPRICE, 0)
      + COALESCE(OSPRICE, 0)
    ) AS TOTAL_PRICE

FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERVALUE
GROUP BY
    JOBNUMBER,
    COMPONENTNUMBER;


CREATE OR REPLACE TABLE DATA_VALIDATION.MART_REVENUE.AR_TRANSACTION_LINE_AGG AS
SELECT
    JOBNUMBER,
    COMPONENTNUMBER,

    COUNT(DISTINCT TRANSACTIONNUMBER) AS AR_TRANSACTION_COUNT,
    SUM(NETVAL) AS AR_NETVAL,
    SUM(TOTALVAL) AS AR_TOTALVAL,
    SUM(COSTVAL) AS AR_COSTVAL

FROM DATA_VALIDATION.RAW_SQL_SERVER.ARTRANSACTIONLINE
GROUP BY
    JOBNUMBER,
    COMPONENTNUMBER;


CREATE OR REPLACE TABLE DATA_VALIDATION.MART_REVENUE.SHIPMENT_AGG AS
SELECT
    JOBNUMBER,
    SCHEDULEDSHIPCOMPONENT AS COMPONENTNUMBER,

    COUNT(DISTINCT SHIPMENTNUMBER) AS SHIPMENT_COUNT,
    MIN(SCHEDULEDSHIPDATE) AS FIRST_SCHEDULED_SHIP_DATE_RAW,
    MAX(SCHEDULEDSHIPDATE) AS LAST_SCHEDULED_SHIP_DATE_RAW,

    TO_DATE(TO_TIMESTAMP_NTZ(MIN(SCHEDULEDSHIPDATE) / 1000000000)) AS FIRST_SCHEDULED_SHIP_DATE,
    TO_DATE(TO_TIMESTAMP_NTZ(MAX(SCHEDULEDSHIPDATE) / 1000000000)) AS LAST_SCHEDULED_SHIP_DATE,

    SUM(SCHEDULEDSHIPQUANTITY) AS SCHEDULED_SHIP_QUANTITY,
    MAX(SHIPPED) AS HAS_SHIPPED_FLAG

FROM DATA_VALIDATION.RAW_SQL_SERVER.SHIPMENT
GROUP BY
    JOBNUMBER,
    SCHEDULEDSHIPCOMPONENT;


CREATE OR REPLACE TABLE DATA_VALIDATION.MART_REVENUE.ORDER_PROCESS_AGG AS
SELECT
    JOBNUMBER,
    COMPONENTNUMBER,

    COUNT(*) AS PROCESS_ROW_COUNT,
    COUNT(DISTINCT PROCESSID) AS PROCESS_COUNT,
    COUNT(DISTINCT PROCESSCODE) AS PROCESS_CODE_COUNT,
    COUNT(DISTINCT MATERIALCODE) AS MATERIAL_CODE_COUNT,
    COUNT(DISTINCT VENDORID) AS PROCESS_VENDOR_COUNT,

    SUM(PRODUCTIONQUANTITY) AS PROCESS_PRODUCTION_QUANTITY,
    SUM(FIXEDCOST) AS PROCESS_FIXED_COST,
    SUM(FIXEDQUANTITY) AS PROCESS_FIXED_QUANTITY,
    SUM(SHEETSPOILAGE) AS PROCESS_SHEET_SPOILAGE,
    SUM(SETUPSPOILAGE) AS PROCESS_SETUP_SPOILAGE,
    SUM(ONESIDEDSHEETS) AS PROCESS_ONE_SIDED_SHEETS,
    SUM(TWOSIDEDSHEETS) AS PROCESS_TWO_SIDED_SHEETS,
    SUM(BLANKSHEETS) AS PROCESS_BLANK_SHEETS,

    MAX(ADDITIONALCHARGE) AS HAS_ADDITIONAL_CHARGE_FLAG,
    MAX(RUSHCHARGE::NUMBER) AS HAS_RUSH_CHARGE_FLAG

FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERPROCESS
GROUP BY
    JOBNUMBER,
    COMPONENTNUMBER;


/*==============================================================================
02 - FACT TABLE
==============================================================================*/

CREATE OR REPLACE TABLE DATA_VALIDATION.MART_REVENUE.FACT_ORDER_COMPONENT AS
SELECT
    oh.JOBNUMBER,
    oh.ESTIMATENUMBER,
    oh.PLANTID,

    oh.CUSTACCOUNT,
    oh.CUSTNAME,

    oh.ORDERDATE AS ORDERDATE_RAW,
    TO_DATE(TO_TIMESTAMP_NTZ(oh.ORDERDATE / 1000000000)) AS ORDER_DATE,

    oh.DUEDATE AS DUEDATE_RAW,
    TO_DATE(TO_TIMESTAMP_NTZ(oh.DUEDATE / 1000000000)) AS DUE_DATE,

    oh.JOBSTATUS,
    oh.STATUS AS ORDER_STATUS_CODE,
    oh.SALESREPCODE,

    oh.TOTALSELLPRICE AS HEADER_TOTAL_SELL_PRICE,
    oh.ORDERSELLPRICE,
    oh.INVOICESELLPRICE,

    oc.COMPONENTNUMBER,
    oc.DESCRIPTION AS COMPONENT_DESCRIPTION,
    oc.COMPONENTTYPE,
    oc.QUANTITYORDERED,
    oc.TOTALSELLPRICE AS COMPONENT_TOTAL_SELL_PRICE,

    v.PRODUCTIONCOST,
    v.MATERIALCOST,
    v.OSCOST,
    v.PRODUCTIONPRICE,
    v.MATERIALPRICE,
    v.OSPRICE,
    v.TOTAL_COST,
    v.TOTAL_PRICE,

    ar.AR_TRANSACTION_COUNT,
    ar.AR_NETVAL,
    ar.AR_TOTALVAL,
    ar.AR_COSTVAL,

    s.SHIPMENT_COUNT,
    s.FIRST_SCHEDULED_SHIP_DATE_RAW,
    s.LAST_SCHEDULED_SHIP_DATE_RAW,
    s.FIRST_SCHEDULED_SHIP_DATE,
    s.LAST_SCHEDULED_SHIP_DATE,
    s.SCHEDULED_SHIP_QUANTITY,
    s.HAS_SHIPPED_FLAG,

    p.PROCESS_ROW_COUNT,
    p.PROCESS_COUNT,
    p.PROCESS_CODE_COUNT,
    p.MATERIAL_CODE_COUNT,
    p.PROCESS_VENDOR_COUNT,
    p.PROCESS_PRODUCTION_QUANTITY,
    p.PROCESS_FIXED_COST,
    p.PROCESS_FIXED_QUANTITY,
    p.PROCESS_SHEET_SPOILAGE,
    p.PROCESS_SETUP_SPOILAGE,
    p.PROCESS_ONE_SIDED_SHEETS,
    p.PROCESS_TWO_SIDED_SHEETS,
    p.PROCESS_BLANK_SHEETS,
    p.HAS_ADDITIONAL_CHARGE_FLAG,
    p.HAS_RUSH_CHARGE_FLAG

FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERHEADER oh

LEFT JOIN DATA_VALIDATION.RAW_SQL_SERVER.ORDERCOMPONENT oc
    ON oh.JOBNUMBER = oc.JOBNUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.ORDER_VALUE_AGG v
    ON oc.JOBNUMBER = v.JOBNUMBER
   AND oc.COMPONENTNUMBER = v.COMPONENTNUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.AR_TRANSACTION_LINE_AGG ar
    ON oc.JOBNUMBER = ar.JOBNUMBER
   AND oc.COMPONENTNUMBER = ar.COMPONENTNUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.SHIPMENT_AGG s
    ON oc.JOBNUMBER = s.JOBNUMBER
   AND oc.COMPONENTNUMBER = s.COMPONENTNUMBER

LEFT JOIN DATA_VALIDATION.MART_REVENUE.ORDER_PROCESS_AGG p
    ON oc.JOBNUMBER = p.JOBNUMBER
   AND oc.COMPONENTNUMBER = p.COMPONENTNUMBER;


/*==============================================================================
03 - DIMENSIONS
==============================================================================*/

CREATE OR REPLACE TABLE DATA_VALIDATION.MART_REVENUE.DIM_CUSTOMER AS
WITH ranked AS (
    SELECT
        CUSTACCOUNT,
        CUSTNAME,
        PLANTID,
        CUSTADDRESS1,
        CUSTADDRESS2,
        CUSTCITY,
        CUSTSTATE,
        CUSTZIP,
        CUSTCOUNTRY,
        CUSTPHONE,
        CUSTEMAIL,
        SALESREPCODE,
        CSR,
        UPDATEDATIM,
        CREATEDATIM,

        ROW_NUMBER() OVER (
            PARTITION BY CUSTACCOUNT
            ORDER BY UPDATEDATIM DESC NULLS LAST, CREATEDATIM DESC NULLS LAST
        ) AS rn

    FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERHEADER
    WHERE CUSTACCOUNT IS NOT NULL
)
SELECT
    CUSTACCOUNT,
    CUSTNAME,
    PLANTID,
    CUSTADDRESS1,
    CUSTADDRESS2,
    CUSTCITY,
    CUSTSTATE,
    CUSTZIP,
    CUSTCOUNTRY,
    CUSTPHONE,
    CUSTEMAIL,
    SALESREPCODE,
    CSR
FROM ranked
WHERE rn = 1;


CREATE OR REPLACE TABLE DATA_VALIDATION.MART_REVENUE.DIM_SALESREP AS
WITH ranked AS (
    SELECT
        SALESREPCODE,
        CUSTACCOUNT,
        CUSTNAME,
        PLANTID,
        CSR,
        UPDATEDATIM,
        CREATEDATIM,

        ROW_NUMBER() OVER (
            PARTITION BY SALESREPCODE
            ORDER BY UPDATEDATIM DESC NULLS LAST, CREATEDATIM DESC NULLS LAST
        ) AS rn

    FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERHEADER
    WHERE SALESREPCODE IS NOT NULL
)
SELECT
    SALESREPCODE,
    CUSTACCOUNT,
    CUSTNAME,
    PLANTID,
    CSR
FROM ranked
WHERE rn = 1;


CREATE OR REPLACE TABLE DATA_VALIDATION.MART_REVENUE.DIM_PLANT AS
SELECT
    PLANTID,
    COUNT(DISTINCT JOBNUMBER) AS JOB_COUNT,
    COUNT(DISTINCT CUSTACCOUNT) AS CUSTOMER_COUNT,
    MIN(ORDERDATE) AS FIRST_ORDER_DATE_RAW,
    MAX(ORDERDATE) AS LAST_ORDER_DATE_RAW,
    TO_DATE(TO_TIMESTAMP_NTZ(MIN(ORDERDATE) / 1000000000)) AS FIRST_ORDER_DATE,
    TO_DATE(TO_TIMESTAMP_NTZ(MAX(ORDERDATE) / 1000000000)) AS LAST_ORDER_DATE
FROM DATA_VALIDATION.RAW_SQL_SERVER.ORDERHEADER
WHERE PLANTID IS NOT NULL
GROUP BY PLANTID;


/*==============================================================================
04 - ANALYTICS VIEW
==============================================================================*/

CREATE OR REPLACE VIEW DATA_VALIDATION.MART_REVENUE.V_ORDER_COMPONENT_ANALYTICS AS
SELECT
    f.*,

    c.CUSTNAME AS DIM_CUSTNAME,
    c.CUSTCITY,
    c.CUSTSTATE,
    c.CUSTCOUNTRY,
    c.CUSTEMAIL,

    c.SALESREPCODE AS CUSTOMER_SALESREPCODE,
    c.CSR AS CUSTOMER_CSR,

    sr.CSR AS SALESREP_CSR,
    sr.PLANTID AS SALESREP_PLANTID,

    p.JOB_COUNT AS PLANT_JOB_COUNT,
    p.CUSTOMER_COUNT AS PLANT_CUSTOMER_COUNT,
    p.FIRST_ORDER_DATE AS PLANT_FIRST_ORDER_DATE,
    p.LAST_ORDER_DATE AS PLANT_LAST_ORDER_DATE

FROM DATA_VALIDATION.MART_REVENUE.FACT_ORDER_COMPONENT f

LEFT JOIN DATA_VALIDATION.MART_REVENUE.DIM_CUSTOMER c
    ON f.CUSTACCOUNT = c.CUSTACCOUNT

LEFT JOIN DATA_VALIDATION.MART_REVENUE.DIM_SALESREP sr
    ON f.SALESREPCODE = sr.SALESREPCODE

LEFT JOIN DATA_VALIDATION.MART_REVENUE.DIM_PLANT p
    ON f.PLANTID = p.PLANTID;


/*==============================================================================
05 - BUSINESS SUMMARY TABLES
==============================================================================*/

CREATE OR REPLACE TABLE DATA_VALIDATION.MART_REVENUE.MONTHLY_REVENUE_SUMMARY AS
SELECT
    DATE_TRUNC('MONTH', ORDER_DATE) AS ORDER_MONTH,

    PLANTID,
    CUSTACCOUNT,
    DIM_CUSTNAME,
    SALESREPCODE,

    COUNT(DISTINCT JOBNUMBER) AS JOB_COUNT,
    COUNT(DISTINCT JOBNUMBER || '-' || COALESCE(COMPONENTNUMBER::TEXT, '')) AS COMPONENT_COUNT,

    SUM(HEADER_TOTAL_SELL_PRICE) AS HEADER_TOTAL_SELL_PRICE,
    SUM(COMPONENT_TOTAL_SELL_PRICE) AS COMPONENT_TOTAL_SELL_PRICE,

    SUM(TOTAL_COST) AS TOTAL_COST,
    SUM(TOTAL_PRICE) AS TOTAL_PRICE,

    SUM(AR_NETVAL) AS AR_NETVAL,
    SUM(AR_TOTALVAL) AS AR_TOTALVAL,
    SUM(AR_COSTVAL) AS AR_COSTVAL,

    SUM(SCHEDULED_SHIP_QUANTITY) AS SCHEDULED_SHIP_QUANTITY

FROM DATA_VALIDATION.MART_REVENUE.V_ORDER_COMPONENT_ANALYTICS
WHERE ORDER_DATE IS NOT NULL
GROUP BY
    ORDER_MONTH,
    PLANTID,
    CUSTACCOUNT,
    DIM_CUSTNAME,
    SALESREPCODE;


/*==============================================================================
06 - BUSINESS-FACING VIEWS
==============================================================================*/

CREATE OR REPLACE VIEW DATA_VALIDATION.MART_REVENUE.V_MONTHLY_REVENUE_TRENDS AS
SELECT
    ORDER_MONTH,
    PLANTID,
    SALESREPCODE,

    COUNT(DISTINCT CUSTACCOUNT) AS CUSTOMER_COUNT,
    SUM(JOB_COUNT) AS JOB_COUNT,
    SUM(COMPONENT_COUNT) AS COMPONENT_COUNT,

    SUM(COMPONENT_TOTAL_SELL_PRICE) AS COMPONENT_REVENUE,
    SUM(TOTAL_COST) AS TOTAL_COST,
    SUM(TOTAL_PRICE) AS TOTAL_PRICE,

    SUM(AR_NETVAL) AS AR_NETVAL,
    SUM(AR_TOTALVAL) AS AR_TOTALVAL,

    SUM(COMPONENT_TOTAL_SELL_PRICE) - SUM(TOTAL_COST) AS ESTIMATED_MARGIN

FROM DATA_VALIDATION.MART_REVENUE.MONTHLY_REVENUE_SUMMARY
GROUP BY
    ORDER_MONTH,
    PLANTID,
    SALESREPCODE;


CREATE OR REPLACE VIEW DATA_VALIDATION.MART_REVENUE.V_TOP_CUSTOMERS AS
SELECT
    CUSTACCOUNT,
    DIM_CUSTNAME,

    COUNT(DISTINCT ORDER_MONTH) AS ACTIVE_MONTHS,
    SUM(JOB_COUNT) AS JOB_COUNT,
    SUM(COMPONENT_COUNT) AS COMPONENT_COUNT,

    SUM(COMPONENT_TOTAL_SELL_PRICE) AS COMPONENT_REVENUE,
    SUM(TOTAL_COST) AS TOTAL_COST,
    SUM(COMPONENT_TOTAL_SELL_PRICE) - SUM(TOTAL_COST) AS ESTIMATED_MARGIN

FROM DATA_VALIDATION.MART_REVENUE.MONTHLY_REVENUE_SUMMARY
GROUP BY
    CUSTACCOUNT,
    DIM_CUSTNAME;


CREATE OR REPLACE VIEW DATA_VALIDATION.MART_REVENUE.V_SALESREP_PERFORMANCE AS
SELECT
    SALESREPCODE,

    COUNT(DISTINCT CUSTACCOUNT) AS CUSTOMER_COUNT,
    COUNT(DISTINCT ORDER_MONTH) AS ACTIVE_MONTHS,

    SUM(JOB_COUNT) AS JOB_COUNT,
    SUM(COMPONENT_COUNT) AS COMPONENT_COUNT,

    SUM(COMPONENT_TOTAL_SELL_PRICE) AS COMPONENT_REVENUE,
    SUM(TOTAL_COST) AS TOTAL_COST,
    SUM(COMPONENT_TOTAL_SELL_PRICE) - SUM(TOTAL_COST) AS ESTIMATED_MARGIN

FROM DATA_VALIDATION.MART_REVENUE.MONTHLY_REVENUE_SUMMARY
GROUP BY SALESREPCODE;


CREATE OR REPLACE VIEW DATA_VALIDATION.MART_REVENUE.V_PLANT_PERFORMANCE AS
SELECT
    PLANTID,

    COUNT(DISTINCT CUSTACCOUNT) AS CUSTOMER_COUNT,
    COUNT(DISTINCT ORDER_MONTH) AS ACTIVE_MONTHS,

    SUM(JOB_COUNT) AS JOB_COUNT,
    SUM(COMPONENT_COUNT) AS COMPONENT_COUNT,

    SUM(COMPONENT_TOTAL_SELL_PRICE) AS COMPONENT_REVENUE,
    SUM(TOTAL_COST) AS TOTAL_COST,
    SUM(COMPONENT_TOTAL_SELL_PRICE) - SUM(TOTAL_COST) AS ESTIMATED_MARGIN

FROM DATA_VALIDATION.MART_REVENUE.MONTHLY_REVENUE_SUMMARY
GROUP BY PLANTID;


/*==============================================================================
07 - DATA QUALITY CHECKS
==============================================================================*/

CREATE OR REPLACE TABLE DATA_VALIDATION.DATA_VALIDATION_DEV.MART_QUALITY_CHECKS AS
SELECT
    CURRENT_TIMESTAMP() AS CHECKED_AT,
    'FACT_ORDER_COMPONENT' AS TABLE_NAME,

    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT JOBNUMBER) AS DISTINCT_JOBS,
    COUNT(DISTINCT JOBNUMBER || '-' || COALESCE(COMPONENTNUMBER::TEXT, '')) AS DISTINCT_JOB_COMPONENTS,

    COUNT_IF(JOBNUMBER IS NULL) AS NULL_JOBNUMBER_COUNT,
    COUNT_IF(COMPONENTNUMBER IS NULL) AS NULL_COMPONENTNUMBER_COUNT,
    COUNT_IF(CUSTACCOUNT IS NULL) AS NULL_CUSTACCOUNT_COUNT,

    COUNT_IF(ORDER_DATE IS NULL) AS NULL_ORDER_DATE_COUNT,
    COUNT_IF(COMPONENT_TOTAL_SELL_PRICE IS NULL) AS NULL_COMPONENT_TOTAL_SELL_PRICE_COUNT

FROM DATA_VALIDATION.MART_REVENUE.FACT_ORDER_COMPONENT;


/*==============================================================================
08 - POST-BUILD VALIDATION QUERIES
==============================================================================*/

SELECT
    'FACT_ORDER_COMPONENT' AS OBJECT_NAME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT JOBNUMBER) AS DISTINCT_JOBS,
    COUNT(DISTINCT JOBNUMBER || '-' || COALESCE(COMPONENTNUMBER::TEXT, '')) AS DISTINCT_JOB_COMPONENTS
FROM DATA_VALIDATION.MART_REVENUE.FACT_ORDER_COMPONENT;


SELECT
    'DIM_CUSTOMER' AS OBJECT_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT CUSTACCOUNT) AS DISTINCT_CUSTOMERS
FROM DATA_VALIDATION.MART_REVENUE.DIM_CUSTOMER;


SELECT
    'DIM_SALESREP' AS OBJECT_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT SALESREPCODE) AS DISTINCT_SALESREPS
FROM DATA_VALIDATION.MART_REVENUE.DIM_SALESREP;


SELECT
    'DIM_PLANT' AS OBJECT_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT PLANTID) AS DISTINCT_PLANTS
FROM DATA_VALIDATION.MART_REVENUE.DIM_PLANT;


SELECT
    'V_ORDER_COMPONENT_ANALYTICS' AS OBJECT_NAME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT JOBNUMBER || '-' || COALESCE(COMPONENTNUMBER::TEXT, '')) AS DISTINCT_JOB_COMPONENTS
FROM DATA_VALIDATION.MART_REVENUE.V_ORDER_COMPONENT_ANALYTICS;


SELECT *
FROM DATA_VALIDATION.DATA_VALIDATION_DEV.MART_QUALITY_CHECKS;


SELECT *
FROM DATA_VALIDATION.MART_REVENUE.MONTHLY_REVENUE_SUMMARY
ORDER BY ORDER_MONTH DESC
LIMIT 100;
